### ISSUE TITLE
每日推荐的歌曲一直没有变化

### ISSUE THREAD

**Issue by ChenSino** [go-musicfox/go-musicfox#102]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

扫码登录，打开每日推荐歌曲，发现一直没有变化，每天都是一样的

### Environment / 运行环境

系统：Manjaro
Version: v4.0.5-6-g7552594

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
对比下网易云的每日推荐看看，直接调的网易云接口，理论上应该和网易云的一样

**Comment by ChenSino** [comment]
> 对比下网易云的每日推荐看看，直接调的网易云接口，理论上应该和网易云的一样

ok，今天一打开就发现和昨天的每日推荐不一样了，我在观察一下。
