### ISSUE TITLE
无法使用邮箱密码登录

### ISSUE THREAD

**Issue by Tenshi65535** [go-musicfox/go-musicfox#106]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

无法使用邮箱密码登录

提示密码错误但并无错误(客户端等均可登录)

### Environment / 运行环境

Windows 11 Pro Build 10.0.25357

go-musicfox version: v4.0.6

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

[musicfox.log](https://github.com/go-musicfox/go-musicfox/files/11419811/musicfox.log)

**Comment by Tenshi65535** [comment]
似乎与 Binaryify/NeteaseCloudMusicApi#1734 类似

**Comment by anhoder** [comment]
扫码登录呢

**Comment by Tenshi65535** [comment]
扫码登陆没问题
