### ISSUE TITLE
为 Linux 添加对 XDG 基本目录规范的支持

### ISSUE THREAD

**Issue by WhiredPlanck** [go-musicfox/go-musicfox#107]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

FreeDesktop 组织为 Linux 下的应用程序制定了一套[基本目录规范](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)，应用程序应当支持这套规范，使用规范制定的环境变量来存储配置、数据和缓存文件等。

我注意到 https://github.com/go-musicfox/go-musicfox/blob/d63897e3554358a3757903b2deb2e9c97c2dc7a5/utils/utils.go#L38-L55 单独定义了一个环境变量来设置本地数据目录，或许可考虑未设置其时默认为 `$XDG_CONFIG_HOME/go-musicfox` 或者 `$HOME/.config/go-musicfox`?

#### 代码参考
1. [kraftkit/config/config_file.go](https://github.com/unikraft/kraftkit/blob/3936ba404420aac16b96e99930f032a6f5ade19d/config/config_file.go)
2. [delve/pkg/config/config.go](https://github.com/go-delve/delve/blob/e95ae9c21b9e4d492538c37a27720eeab6d894d1/pkg/config/config.go)

**Comment by anhoder** [comment]
v4.1.0

**Comment by WhiredPlanck** [comment]
@anhoder 感谢 ～
