### ISSUE TITLE
mpris 获取到的歌曲播放进度始终为0

### ISSUE THREAD

**Issue by bpking1** [go-musicfox/go-musicfox#114]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

playerctl metadata --format '{{ duration(position) }}'
返回结果始终为0:00,没有正确返回当前播放进度

源码中好像实现了这个方法 
https://github.com/go-musicfox/go-musicfox/blob/0e7d86cea14a9f26337815e7da0b9848d3b02be4/pkg/state_handler/mpris_player.go#L87
不太熟悉go语言，不知道原因是啥

### Environment / 运行环境

archlinux
Version: v4.1.1-3-g2d778ad

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by NobodyHere-rrr** [comment]
若使用的是mpd, 安装mpdris2 (AUR), 并连接至同一端口, 则可正常获取播放进度.

**Comment by NobodyHere-rrr** [comment]
> ![swappy-20230718_123454](http://user-images.githubusercontent.com/62543054/254140707-b8211d3d-a44e-4e38-b62f-caf8ff754d9e.png) 若使用的是mpd, 安装mpdris2-rs (AUR), 并连接至同一端口, 则可正常获取播放进度.

现在似乎又不行了
