### ISSUE TITLE
Windows11无显示

### ISSUE THREAD

**Issue by debfig** [go-musicfox/go-musicfox#115]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

windows 11 ps 下使用 go run .\musicfox.go

### Environment / 运行环境

主机名:           LAPTOP-G3K136Q7
OS 名称:          Microsoft Windows 11 家庭中文版
OS 版本:          10.0.22621 暂缺 Build 22621
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     灿烈
注册的组织:       暂缺
产品 ID:          00342-30407-90975-AAOEM
初始安装日期:     2023/2/22, 18:34:24
系统启动时间:     2023/6/3, 20:52:47
系统制造商:       LENOVO
系统型号:         82NC
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 140 Stepping 2 GenuineIntel ~3187 Mhz
BIOS 版本:        LENOVO FJCN65WW, 2021/7/22
Windows 目录:     C:\WINDOWS
系统目录:         C:\WINDOWS\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     16,167 MB
可用的物理内存:   5,433 MB
虚拟内存: 最大值: 27,943 MB
虚拟内存: 可用:   12,866 MB
虚拟内存: 使用中: 15,077 MB
页面文件位置:     C:\pagefile.sys
域:               WORKGROUP
登录服务器:       \\LAPTOP-G3K136Q7
修补程序:         安装了 4 个修补程序。
                  [01]: KB5022497
                  [02]: KB5012170
                  [03]: KB5025239
                  [04]: KB5025749
网卡:             安装了 3 个 NIC。
                  [01]: VMware Virtual Ethernet Adapter for VMnet1
                      连接名:      VMware Network Adapter VMnet1
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.234.254
                      IP 地址
                        [01]: 192.168.234.1
                        [02]: fe80::cb4f:4acf:ac2a:4919
                  [02]: VMware Virtual Ethernet Adapter for VMnet8
                      连接名:      VMware Network Adapter VMnet8
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.75.254
                      IP 地址
                        [01]: 192.168.75.1
                        [02]: fe80::752f:c160:7ddd:9073
                  [03]: Intel(R) Wi-Fi 6 AX201 160MHz
                      连接名:      WLAN
                      启用 DHCP:   是
                      DHCP 服务器: 10.139.4.6
                      IP 地址
                        [01]: 10.105.239.3
                        [02]: fe80::9d7e:e046:db0:ca3e
Hyper-V 要求:     已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by kylezb** [comment]
请详细描述问题，否则无法排查
检查版本以及确认此前确认是否使用过该程序，4.10以后的版本可能需要手动删除之前版本的配置文件夹

**Comment by kylezb** [comment]
试试清空用户文件夹下的 .go-musicfox 或者 AppData\Roaming\go-musicfox的内容（如果有的话，记得备份）
