### ISSUE TITLE
添加歌曲到喜欢歌单报错「网络拥挤」

### ISSUE THREAD

**Issue by sunwgit** [go-musicfox/go-musicfox#122]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

点击逗号「，」添加或者移除喜欢的歌曲歌单，会弹出「网络太拥挤。。。」的通知

### Environment / 运行环境

MacOS Ventura 13.4
intel core i5 2.3GHz
musicfox 4.1.2

### If applicable, list the error messages you see
如果有错误输出请一并填入

2023/06/14 13:02:39 url: https://music.163.com/weapi/playlist/manipulate/tracks, method: POST, reqData: map[string]string{"encSecKey":"7a01e38d1902c8d3e50e6686a44e1229a8c0367fe769c5465ba00adb34c9edebcc538d7ab5c876961bdf1bafe976879f0cad349b6448af84527b815ac25c83d633f1cc14886e971b2956728bd5a39ae6008aa7099ea784dc53c7013599f18eec5d3ae2c00f7bb9c6a82a1a0fde473ad300abd7a531549d64bf6b5b430b0493ca", "params":"ydaPMQudw82gV3pdCY81Es+t2Ov0pzA4JJPGi1rxZ2vfyBkwLNTJ4gDmnAZ0ze5HLzRh0PvpY5iUIzTC7ftBEjB3l3kUdBGNPoddS9jKyZQjjXUAPHE+fP6CzsmFN3EdD75w2jyAJ8abpFbeF1KnvjEzmX3FluYgZxnvQOSntAFM2ZKrrkEoXFcLG4qllx/g4HOL5WoKrC2RbgEj39viZEdXMWVCzN6yY+XvEbmdP/g="}, reqOptions: &{Crypto:weapi Ua: Cookies:[NMTID=00OFZnNNOvYykzuGEL9guJ8MCUpbxwAAAGG2uZ0og MUSIC_U=add03758d95797c0a27d577166d25df38376c22d969ce0aae9307f44123c86105b0dd7572643488b714042368caae72d63f5429ccd49e667374e517199375677c0ce5c925a235d13ad8b3b53860f12d6 __csrf=251262666f5b6286d8393603899b4896] Token: Url: SkipUNM:false}, resCode: -462.000000, resResp: {"code":-462,"data":{"actionCode":"1102401","verifyType":50,"verifyId":1,"verifyUrl":"","blockText":"网络太拥挤，请稍候再试。","verifyToken":null,"btnText":null,"orpheusUrl":null,"frontRuleIds":[1102401],"params":{"event_id":"00376957499893792787","sign":"c7c8b113d39f542a5bc81ef7ecc9f476"},"url":null},"message":"网络太拥挤，请稍候再试。"}, resCookies: []*http.Cookie{(*http.Cookie)(0xc0002b2000), (*http.Cookie)(0xc0002b2370), (*http.Cookie)(0xc0002b2420), (*http.Cookie)(0xc0002b24d0), (*http.Cookie)(0xc0002b2580), (*http.Cookie)(0xc0002b2630), (*http.Cookie)(0xc0002b26e0), (*http.Cookie)(0xc0002b2790), (*http.Cookie)(0xc0002b2840), (*http.Cookie)(0xc0002b28f0)}

**Comment by anhoder** [comment]
重新登录试试
