### ISSUE TITLE
加载程序后进行自动播放

### ISSUE THREAD

**Issue by 18271211** [go-musicfox/go-musicfox#127]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

能不能很简单的加个功能，加载程序后根据ini的配置，判断是否自动播放喜欢的音乐，今日推荐音乐或者私人FM等等，这样的话就能把程序加到systemd开机自动运行，设备通电后开机自动开始播放背景音乐

**Comment by imxyy1soope1** [comment]
已经提了pr,等merge。
见#134
