### ISSUE TITLE
使用mpd作为播放器的情况下，程序非正常退出不会杀掉mpd进程

### ISSUE THREAD

**Issue by 18271211** [go-musicfox/go-musicfox#128]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

使用mpd作为播放器的情况下，程序非正常退出不会杀掉mpd进程，造成再次运行时由于mpd运行错误导致程序无法运行，必须手动杀一次mpd进程。
建议可以在初始加载的时候，自动运行一次mpd --kill, 无需pid的辅助，mpd会自动查找进程杀掉。

### Environment / 运行环境

debian  arm64

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
已实现，启动时会执行一次kill操作
