### ISSUE TITLE
希望添加到winget库中

### ISSUE THREAD

**Issue by Sisyphean-a** [go-musicfox/go-musicfox#142]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

现在winget的生态相当完善，绝大多数的Windows软件都可以使用winget进行安装，例如微信qq各种网盘等国产应用、idea python等绝大多数编程相关应用 、YesPlayMusic LocalSend等GitHub应用
希望这个项目也能进入winget库中

**Comment by amalaccs** [comment]
+1

**Comment by anhoder** [comment]
有文档吗

**Comment by amalaccs** [comment]
> 有文档吗

[winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by anhoder** [comment]
https://github.com/microsoft/winget-pkgs/pull/112217
已合并
