### ISSUE TITLE
云盘中的歌曲只能查看前100首, 歌单中的歌曲只能查看前1000首

### ISSUE THREAD

**Issue by NobodyHere-rrr** [go-musicfox/go-musicfox#143]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

查看云盘中的歌曲时，只能查看到前100首（到编号99为止）；查看歌单中的歌曲时，只能查看到前1000首。

### Environment / 运行环境

macOS Ventura 13.3
arm64
musicfox 4.1.2

### If applicable, list the error messages you see
如果有错误输出请一并填入

无

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

无

**Comment by anhoder** [comment]
云盘翻页已修复 

歌单限制1000请修改配置文件
```ini
# 是否显示歌单下所有歌曲，默认不开启，仅获取歌单前1000首，开启后可能会占用更多内存（大量歌曲数据）和带宽（会同时发送多个请求获取歌单下歌曲数据）
showAllSongsOfPlaylist=false
```

**Comment by NobodyHere-rrr** [comment]
> 云盘翻页已修复
> 
> 歌单限制1000请修改配置文件
> 
> ```ini
> # 是否显示歌单下所有歌曲，默认不开启，仅获取歌单前1000首，开启后可能会占用更多内存（大量歌曲数据）和带宽（会同时发送多个请求获取歌单下歌曲数据）
> showAllSongsOfPlaylist=false
> ```

请问通过Homebrew (macOS) 安装后的配置文件的位置是？

**Comment by anhoder** [comment]
执行`musicfox config`可以看到
