### ISSUE TITLE
使用mpd作为播放引擎时无法调整音量

### ISSUE THREAD

**Issue by NobodyHere-rrr** [go-musicfox/go-musicfox#145]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

如题，无法通过 ‘-’ 与 ‘=’ 键调整音量（准确来说是无效）

### Environment / 运行环境

OS: Arch Linux 6.4.2-zen1-1-zen
CPU Arch: x86_64
go-musicfox: 4.1.2
mpd: 0.23.13

### If applicable, list the error messages you see
如果有错误输出请一并填入

无

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

无

**Comment by NobodyHere-rrr** [comment]
> 用master代码编译执行，`=/-`调节音量后，看下`~/.go-msicfox/musicfox.log`中的有没有错误日志

并没有，如不是我手动创建甚至连这个文件夹（~/.go-musicfox）都不存在。

**Comment by anhoder** [comment]
执行下`musicfox config`看配置文件在哪

**Comment by NobodyHere-rrr** [comment]
> 执行下`musicfox config`看配置文件在哪

~/.config/go-musicfox/go-musicfox.ini

**Comment by anhoder** [comment]
`command 'setvol' failed: Failed to set mixer for 'audio'; no such mixer control: PCM`
你的mpd调节不了音量，具体问题自行搜索这个错误
