### ISSUE TITLE
歌曲下載不完整

### ISSUE THREAD

**Issue by fuyu0425** [go-musicfox/go-musicfox#149]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

調高音質或長度過長，歌曲下載不完整。

測試歌曲: 幻想楼閣 - 橋本みゆき

當`songLevel=higher`時，檔案大概 7MB，歌曲完整 (4:48)。
`songLevel=exhigh` 時，檔案大概 10MB，歌曲不完整 (4:10 左右)。 
我猜是 server 有 response 大小限制。
我自己有小測試一下，確實 HEAD request 能拿到 size.  

可能準確不是 10M，有時大概 9M 就斷了。

問了一下ChatGPT，

in Go, how to download a big file if the server limit client body to 10m?

If you're attempting to download a large file from a server that limits client body size to 10MB, the server needs to support range requests (also known as byte serving). This will allow your Go client to request portions of the file, instead of attempting to download the entire file in a single request.

Below is an example in Go, which makes HTTP GET requests in chunks of 10MB (10 * 1024 * 1024 bytes) until the whole file is downloaded:

```go
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
)

func main() {
	url := "http://example.com/bigfile" // Replace with your file's URL
	err := DownloadFile(url, "bigfile")
	if err != nil {
		panic(err)
	}
}

// DownloadFile will download a file from a URL and save it to the specified path.
func DownloadFile(url string, filepath string) error {
	resp, err := http.Head(url)
	if err != nil {
		return err
	}

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("server returned %d status: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}

	if resp.Header.Get("Accept-Ranges") != "bytes" {
		return fmt.Errorf("server does not support range requests")
	}

	size, err := strconv.Atoi(resp.Header.Get("Content-Length"))
	if err != nil {
		return err
	}

	file, err := os.Create(filepath)
	if err != nil {
		return err
	}
	defer file.Close()

	for i := 0; i < size; i += 10 * 1024 * 1024 {
		end := i + 10*1024*1024 - 1
		if end > size {
			end = size
		}

		req, err := http.NewRequest("GET", url, nil)
		if err != nil {
			return err
		}
		rangeHeader := "bytes=" + strconv.Itoa(i) + "-" + strconv.Itoa(end)
		req.Header.Add("Range", rangeHeader)

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			return err
		}
		defer resp.Body.Close()

		if resp.StatusCode != http.StatusPartialContent {
			// Fallback to simple download
			if _, err := io.Copy(file, resp.Body); err != nil {
				return err
			}
		}

		if _, err := io.Copy(file, resp.Body); err != nil {
			return err
		}
	}

	return nil
}
```

This code does the following:

1. Makes a HEAD request to get the file size and to check if the server supports range requests. 
2. Checks the server response code and whether it accepts byte serving.
3. Creates the file on local disk.
4. Makes a series of GET requests to download chunks of the file, adding the `Range` header to each request.
5. Writes each chunk to the file.
6. Repeats steps 4 and 5 until the whole file is downloaded.

Please replace `"http://example.com/bigfile"` and `"bigfile"` with your actual URL and destination file path respectively.

### Environment / 运行环境

go-musicfox master branch
OS: macOS 10.15.7

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by fuyu0425** [comment]
順便可以再加個校對，檢查下載完的檔案的音樂時長是不是一致，不然要每個檔案檢查。

**Comment by kylezb** [comment]
Windows v4.1.3 没有复现成功
![1](https://github.com/go-musicfox/go-musicfox/assets/27952150/943c5c52-5cc0-4318-9c1b-131a6aed3806)

**Comment by fuyu0425** [comment]
<img width="836" alt="圖片" src="https://github.com/go-musicfox/go-musicfox/assets/15128056/fa9df2de-8c5b-4bfc-bc22-4202d04f0216">

🤔 用了 windows的機器 一樣 v4.13 還是一樣
@kylezb 你有開通會員之類的嗎?

**Comment by fuyu0425** [comment]
有時會發生，有時不會。
直接 wget 倒是很穩定能下載完。

**Comment by fuyu0425** [comment]
<img width="1084" alt="圖片" src="https://github.com/go-musicfox/go-musicfox/assets/15128056/580b8fc3-7750-483b-a81e-fb2c23c5ad15">
找到錯誤了

```go
_, err = io.Copy(f, resp.Body)
if err != nil {
	errHandler(err)
	return
}
```
發生在 copy時

**Comment by kylezb** [comment]
> <img alt="圖片" width="806" height="17.840909957885742" src="https://user-images.githubusercontent.com/15128056/252986863-580b8fc3-7750-483b-a81e-fb2c23c5ad15.png"> 找到錯誤了   <img alt="圖片" width="806" height="17.840909957885742" src="https://user-images.githubusercontent.com/15128056/252986863-580b8fc3-7750-483b-a81e-fb2c23c5ad15.png"> 找到错误了
> ```go
> _, err = io.Copy(f, resp.Body)
> if err != nil {
> 	errHandler(err)
> 	return
> }🔄  ❓
> ```
> 
> 發生在 copy時 发生在 copy 时

我这一直无法复现成功，每次下载都是正常的。这个看起来像是网络问题，感觉是超时了，你的网络环境用wget最长要多久下载完成。

**Comment by fuyu0425** [comment]
<img width="1345" alt="圖片" src="https://github.com/go-musicfox/go-musicfox/assets/15128056/22cb76c1-303c-42d6-aea2-b7fd901abce7">
人在國外 離 server (在tokyo) 比較遠

**Comment by fuyu0425** [comment]
https://github.com/go-musicfox/go-musicfox/blob/f9444422a620bd1f77580ad207e21040c9b28945/pkg/constants/constants.go#L31

看來是超過 5秒

**Comment by kylezb** [comment]
> <img alt="圖片" width="1345" src="https://user-images.githubusercontent.com/15128056/252997288-22cb76c1-303c-42d6-aea2-b7fd901abce7.png"> 人在國外 離 server (在tokyo) 比較遠

🤔soga，那这样体验可能确实会差一些，正常情况下发生这种事情的概率比较小，我不太确定针对此类报错直接返回下载失败是不是一个好的解决方案，或者说把超时时间放进配置文件？ @anhoder

**Comment by fuyu0425** [comment]
畢竟每個人網速不一樣。
可以對這個獨立設置一個 timeout。
或能根據歌曲時長延長 timeout.

**Comment by anhoder** [comment]
> > <img alt="圖片" width="1345" src="https://user-images.githubusercontent.com/15128056/252997288-22cb76c1-303c-42d6-aea2-b7fd901abce7.png"> 人在國外 離 server (在tokyo) 比較遠
> 
> 🤔soga，那这样体验可能确实会差一些，正常情况下发生这种事情的概率比较小，我不太确定针对此类报错直接返回下载失败是不是一个好的解决方案，或者说把超时时间放进配置文件？ @anhoder

下载歌曲时可以重新new个http.Client，单独设置一个比较长的时间超时时间，同时加上这段错误日志记录：
```go
_, err = io.Copy(f, resp.Body)
if err != nil {
	errHandler(err)
	return
}
```

**Comment by kylezb** [comment]
> > > <img alt="圖片" width="1345" src="https://user-images.githubusercontent.com/15128056/252997288-22cb76c1-303c-42d6-aea2-b7fd901abce7.png"> 人在國外 離 server (在tokyo) 比較遠
> > 
> > 
> > 🤔soga，那这样体验可能确实会差一些，正常情况下发生这种事情的概率比较小，我不太确定针对此类报错直接返回下载失败是不是一个好的解决方案，或者说把超时时间放进配置文件？ @anhoder
> 
> 下载歌曲时可以重新new个http.Client，单独设置一个比较长的超时时间，同时加上这段错误日志记录：
> 
> ```go
> _, err = io.Copy(f, resp.Body)
> if err != nil {
> 	errHandler(err)
> 	return
> }
> ```

可以，30s应该够了吧

**Comment by anhoder** [comment]
要不直接60吧

**Comment by kylezb** [comment]
> 要不直接60吧

可以，我再看看歌名包含分隔符怎么处理比较好

**Comment by anhoder** [comment]
`/`可以考虑直接过滤掉，或者替换为其他字符 例如`:`

**Comment by fuyu0425** [comment]
merge #139 後，這個fix消失了 😢
