### ISSUE TITLE
mpd Last.fm 上報錯誤

### ISSUE THREAD

**Issue by fuyu0425** [go-musicfox/go-musicfox#151]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

https://github.com/go-musicfox/go-musicfox/blob/f9444422a620bd1f77580ad207e21040c9b28945/pkg/ui/player.go#L127

我在這
https://github.com/go-musicfox/go-musicfox/blob/f9444422a620bd1f77580ad207e21040c9b28945/pkg/lastfm/api.go#L153
加了 logger
```go
utils.Logger().Printf("[LASTFM] Report: report phase complete d:%f p:%f",duration,passedSeconds)
```
log裡，passedSeconds都是 0.

似乎上報前 timer 就被  reset了
https://github.com/go-musicfox/go-musicfox/blob/f9444422a620bd1f77580ad207e21040c9b28945/pkg/player/mpd_player.go#L196

### Environment / 运行环境

musicfox master
macOS 10.15.7

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by fuyu0425** [comment]
是不是應該是 `p.playedTime` 🤔

**Comment by fuyu0425** [comment]
https://github.com/go-musicfox/go-musicfox/blob/f9444422a620bd1f77580ad207e21040c9b28945/pkg/ui/player.go#L145-L146

https://github.com/go-musicfox/go-musicfox/blob/f9444422a620bd1f77580ad207e21040c9b28945/pkg/player/osx_player_darwin.go#L83

這裡是 500，是不是忘了改?

**Comment by kylezb** [comment]
具体报错/错误是啥

**Comment by fuyu0425** [comment]
沒報錯 `p.PassedTime()` 在 `lastfm.Report`時是 0 導致
`if duration <= passedSeconds || passedSeconds >= duration/2` 永遠是 false，所以不會上報

**Comment by fuyu0425** [comment]
就是打印出來是 0 (我先改成 p.playedTime了)

```go
	// 状态监听
	go func() {
		defer utils.Recover(false)
		for {
			select {
			case <-ctx.Done():
				return
			case s := <-p.Player.StateChan():
				p.stateHandler.SetPlayingInfo(p.PlayingInfo())
				if s != player.Stopped {
					p.model.Rerender(false)
					break
				}
				utils.Logger().Printf("[LASTFM] StateChan: report complete %f", p.PassedTime().Seconds())
				// 上报lastfm
				lastfm.Report(p.model.lastfm, lastfm.ReportPhaseComplete, p.curSong, p.playedTime)
				// 自动切歌且播放时间不少于(实际歌曲时间-20)秒时，才上报至网易云
				if p.CurMusic().Duration.Seconds()-p.playedTime.Seconds() < 20 {
					utils.ReportSongEnd(p.curSong.Id, p.PlayingInfo().TrackID, p.playedTime)
				}
				p.NextSong(false)
			}
		}
	}()
```

```
2023/07/12 21:42:51 [LASTFM] StateChan: report complete 0.00000
```

**Comment by fuyu0425** [comment]
你是用 mpd嗎？

**Comment by kylezb** [comment]
我用的默认的的beep

**Comment by fuyu0425** [comment]
Beep 沒問題，但播完居然 panic 了.  來測看看 osx
```
[LASTFM] Report: report phase complete d:219.893000 p:219.800000
```
<img width="1039" alt="圖片" src="https://github.com/go-musicfox/go-musicfox/assets/15128056/a631ebc1-182c-45ff-bb41-466a8c5eaf37">

**Comment by fuyu0425** [comment]
`2023/07/12 22:00:21 [LASTFM] Report: report phase complete d:332.733000 p:337.000000`
osx 也沒問題 所以只有mpd有問題。

**Comment by kylezb** [comment]
不应该啊，返回的都是Timer里的passed，这个和播放引擎应该是无关的，奇了怪了

**Comment by fuyu0425** [comment]
`mpd` 裡邏輯不太一樣有個 `SyncMpdStatus`，channel 太多，不太確定順序。

**Comment by kylezb** [comment]
召唤大佬 @anhoder

**Comment by anhoder** [comment]
我晚上看下
