### ISSUE TITLE
快退时歌词不会同步快退

### ISSUE THREAD

**Issue by NobodyHere-rrr** [go-musicfox/go-musicfox#152]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

如题，例如此时歌词为“xxx”，五秒前的歌词为“yyy”，则快退五秒后歌词仍旧显示“xxx”。

### Environment / 运行环境

OS: macOS 13.3
musicfox: 4.1.3
arch: arm64

### If applicable, list the error messages you see
如果有错误输出请一并填入

无

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

无

**Comment by kylezb** [comment]
确认BUG，先用4.1.2吧，这个没问题

**Comment by anhoder** [comment]
fixed https://github.com/go-musicfox/go-musicfox/commit/ae9f57d8623dd87c7a9458022d588ea905dec790
