### ISSUE TITLE
云盘中的音乐无法获取元数据

### ISSUE THREAD

**Issue by NobodyHere-rrr** [go-musicfox/go-musicfox#154]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

上传至云盘的音乐添加了元数据（如歌手，专辑封面等），但是musicfox在播放时无法获取并显示。

### Environment / 运行环境

OS: macOS 13.3
musicfox: 4.1.3
arch: arm64

### If applicable, list the error messages you see
如果有错误输出请一并填入

无

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

无

**Comment by anhoder** [comment]
云盘音乐没办法，网易云没有歌曲信息，播放的音乐文件也没有元数据
