### ISSUE TITLE
云盘中部分音乐无法正常播放

### ISSUE THREAD

**Issue by NobodyHere-rrr** [go-musicfox/go-musicfox#155]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

部分云盘中的音乐在官方客户端中可以正常播放，而在musicfox中只能播放前3~5秒

### Environment / 运行环境

OS: macOS 13.3
musicfox: 4.1.3
arch: arm64

### If applicable, list the error messages you see
如果有错误输出请一并填入

无

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

无

**Comment by anhoder** [comment]
有些云盘歌曲网易云没有时长数据，会出现这个问题，比较麻烦，不打算处理
