### ISSUE TITLE
FLAC 緩存/下載 Deadlock

### ISSUE THREAD

**Issue by fuyu0425** [go-musicfox/go-musicfox#158]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

復現: 下載任一 FLAC file

如果歌曲是 FLAC，在`SetSongTag`會 Deadlock，花了點時間排查。

https://github.com/go-musicfox/go-musicfox/blob/59663906f8b24a7162624a9ca9b3de7d592b4cf3/utils/utils.go#L338

原因是這個 SaveFile，原檔名不能和目標檔名相同。

```go
func (flac *FLAC) SaveFile(path string) error {
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()

	return flac.Save(file)
}
```
他會開一個同名的 File，然後就 Deadlock了。

解決辦法: tmp file

```go
_  = metadata.SaveFile(file.Name() + "-tmp")
os.Rename(file.Name() + "-tmp", file.Name())
```

### Environment / 运行环境

musicfox: master branch
OS: macOS 10.15.7

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by imxyy1soope1** [comment]
我的问题，没考虑看tag的源码

要不你自己提个pr吧，我现在不方便开电脑
