### ISSUE TITLE
自定义已播放的最后一个字符与未播放的第一个字符

### ISSUE THREAD

**Issue by NobodyHere-rrr** [go-musicfox/go-musicfox#166]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

原本的: 
+++++++++++----------------------
++++++++++++---------------------
可以通过修改配置文件变为: 
++++++++++󰮯 󰊠 ---------------------
+++++++++++󰮯 󰊠 --------------------

**Comment by anhoder** [comment]
已支持
> 注意配置有变更
