### ISSUE TITLE
使用mpd作为后端时有时无法调整进度

### ISSUE THREAD

**Issue by NobodyHere-rrr** [go-musicfox/go-musicfox#168]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

如题。
musicfox.log中的报错为 [ERROR] mpdPlayer, err: command 'seekcur' failed: Not seekable

### Environment / 运行环境

OS: Arch Linux x86_64 6.4.4-zen1-1-zen
musicfox: v4.1.4

### If applicable, list the error messages you see
如果有错误输出请一并填入

无

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

如上所述，只有 [ERROR] mpdPlayer, err: command 'seekcur' failed: Not seekable 一种报错。

**Comment by 18271211** [comment]
换一个input 试试，禁用curl， 用ffmpeg 作为http的下载器

**Comment by 18271211** [comment]
input {
        plugin "curl"
        enabled "no"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
}

**Comment by 18271211** [comment]
> 

理论上不会的，应该还是mpd没有配置好。输出这块再好好看一下。
开始播放以后后续都转交给mpd的，musicfox做的只是提供给mpd一个播放链接而已。
