### ISSUE TITLE
较快速度切换歌曲时可能出现实际播放的歌曲与显示正在播放的歌曲不一致

### ISSUE THREAD

**Issue by NobodyHere-rrr** [go-musicfox/go-musicfox#169]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

如题，以下是演示：
![swappy-20230728_152727](https://github.com/go-musicfox/go-musicfox/assets/62543054/20dd5949-728d-4e07-9b4b-dd9240be58f2)
![swappy-20230728_152737](https://github.com/go-musicfox/go-musicfox/assets/62543054/5aaaf244-f982-4245-9d49-b0403cd6c95f)

### Environment / 运行环境

OS: Arch Linux x86_64 6.4.6-zen1-1-zen
musicfox: v4.1.4

### If applicable, list the error messages you see
如果有错误输出请一并填入

无

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

无

**Comment by anhoder** [comment]
musicfox不打算做并发控制
