### ISSUE TITLE
依赖项boltdb/bolt使用了弃用的方法，无法在新版本Go编译

### ISSUE THREAD

**Issue by donmor** [go-musicfox/go-musicfox#173]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

在Go 1.20.4上运行编译报错；大量关键字变为undefined；经查资料推测原因是某些类型在新版本Go中弃用
修改代码使用go.etcd.io/bbolt替换boltdb/bolt后成功编译

### Environment / 运行环境

musicfox: v4.1.4-dev
uname -a: Linux archlinux 6.3.0-13 #1 SMP Tue, 23 May 2023 03:56:45 +0000 loongarch64 GNU/Linux

### If applicable, list the error messages you see
如果有错误输出请一并填入

```
[loongarch@archlinux go-musicfox]$ make
./hack/build.sh build
# github.com/boltdb/bolt
vendor/github.com/boltdb/bolt/db.go:101:13: undefined array length maxMapSize or missing type constraint
vendor/github.com/boltdb/bolt/db.go:317:12: undefined: maxMapSize
vendor/github.com/boltdb/bolt/db.go:335:10: undefined: maxMapSize
vendor/github.com/boltdb/bolt/db.go:336:8: undefined: maxMapSize
vendor/github.com/boltdb/bolt/db.go:795:2: pos declared and not used
vendor/github.com/boltdb/bolt/bolt_unix.go:62:15: undefined array length maxMapSize or missing type constraint
vendor/github.com/boltdb/bolt/bucket.go:135:15: undefined: brokenUnaligned
vendor/github.com/boltdb/bolt/freelist.go:166:2: idx declared and not used
vendor/github.com/boltdb/bolt/freelist.go:169:19: undefined array length maxAllocSize or missing type constraint
vendor/github.com/boltdb/bolt/freelist.go:176:14: undefined array length maxAllocSize or missing type constraint
vendor/github.com/boltdb/bolt/freelist.go:166:2: too many errors
make: *** [Makefile:19: build] Error 1
```

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by imxyy1soope1** [comment]
Arch Linux x86_64, Kernel 6.4.7-zen1-1-zen编译无报错

**Comment by anhoder** [comment]
mac下正常，抱错信息里的maxMapSize只是个bolt包内定义的常量，不涉及golang，可能你改动了什么文件？
<img width="1441" alt="image" src="https://github.com/go-musicfox/go-musicfox/assets/27605589/51f0e700-dd21-45f6-89a9-c481845ea88e">

**Comment by donmor** [comment]
可能我用的是loongarch64架构，然后有什么地方没适配？

**Comment by imxyy1soope1** [comment]
> 可能我用的是loongarch64架构，然后有什么地方没适配？

看起来boltdb并没有适配loongarch64

**Comment by anhoder** [comment]
可以换成go.etcd.io/bbolt

**Comment by anhoder** [comment]
@donmor 已替换为go.etcd.io/bbolt
