### ISSUE TITLE
cli控制音乐播放

### ISSUE THREAD

**Issue by 2403772980ygy** [go-musicfox/go-musicfox#175]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

我想通过cli控制音乐的播放，停止，前进后退。这样的话我就可以简单的添加快捷键了(xmonad)。

我看了wiki，但是确实没有找到很好的解决办法......

如果已经有快捷键支持的话也可以试试xdotool，但是我也没有看到......

**Comment by 2403772980ygy** [comment]
我认为可能可以采取类似mpd和mpc的方法，单独写一个控制端。

**Comment by 18271211** [comment]
> 我认为可能可以采取类似mpd和mpc的方法，单独写一个控制端。

本身支持mpd，用cli的mpd client控制即可

**Comment by zhuxinzzz** [comment]
键盘自带的多媒体快捷键，可以全局控制播放、暂停、切歌。
自己改按键映射也许能解决。

**Comment by 2403772980ygy** [comment]
@NobodyHere-rrr 可能是配置问题， 但是我现在这里完一下，在使用mpd时我有时会出现一些歌无法播放的问题， 播放时会出现时间不定的噪音， 然后自动切歌......  用beep时不会。

不知为何使用mpc无法使用上下曲功能，之后会测试mpris效果。

@zhuxinzzz 在我的配置上不行，想问问是通过dbus吗？有没有什么配置方法？我这里这些快捷键会被当作和abc一样的“按键”处理，直接落到焦点中，比如kitty的终端里面。

**Comment by zhuxinzzz** [comment]
> @NobodyHere-rrr 可能是配置问题， 但是我现在这里完一下，在使用mpd时我有时会出现一些歌无法播放的问题， 播放时会出现时间不定的噪音， 然后自动切歌...... 用beep时不会。
> 
> 不知为何使用mpc无法使用上下曲功能，之后会测试mpris效果。
> 
> @zhuxinzzz 在我的配置上不行，想问问是通过dbus吗？有没有什么配置方法？我这里这些快捷键会被当作和abc一样的“按键”处理，直接落到焦点中，比如kitty的终端里面。

有多媒体控制键的键盘可以直接使用，原理不清楚。运行程序后，可以在全局范围内响应功能键。

以下是一些按键事件，键值的输出。运行showkey程序，按下键盘上的按键，程序将打印出对应的键值。注释是我加上的。
```
~$ sudo showkey -s
0x9c //enter抬起
x0x2d 0xad //x键的按下抬起
y0x15 0x95 //y键的按下抬起
z0x2c 0xac //z键的按下抬起
0xe0 0x10 0xe0 0x90 //上一首键的按下抬起
0xe0 0x22 0xe0 0xa2 //暂停键的按下抬起
0xe0 0x19 0xe0 0x99 //下一首键的按下抬起
0xe0 0x20 0xe0 0xa0 //静音键的按下抬起
0xe0 0x20 0xe0 0xa0 //静音键的按下抬起
0xe0 0x2e 0xe0 0xae //音量加键的按下抬起
0xe0 0x30 0xe0 0xb0 //音量减键的按下抬起
```
希望能帮到你。

**Comment by 2403772980ygy** [comment]
@zhuxinzzz 我认为可能是你的桌面系统提供并配置好了关于多媒体控制的一些工具。

我个人通过xmonad设置快捷键和mpris(playerctl)解决了问题。可能你的系统已经配置好了。

mpd可用性个人认为还是挺好的。我认为可能可以用mocp作为后端备选，但是没有任何急迫性。

**Comment by 2403772980ygy** [comment]
当然， beep的用户现在就折磨一下把......
