### ISSUE TITLE
确定的 mpris 中的 player 名称

### ISSUE THREAD

**Issue by NobodyHere-rrr** [go-musicfox/go-musicfox#176]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

如题，在 mpris 中，musicfox 的 player 名称一般为musicfox.instance[xxxxx]，能否将其确定为 musicfox？这将方便从 mpris 中获取 musicfox 正在播放的歌曲的 metadata。

![图片](https://github.com/go-musicfox/go-musicfox/assets/62543054/be7f4ad1-5dd6-4340-910e-eb1c2e1484bc)

**Comment by imxyy1soope1** [comment]
我这边是确定的musicfox哦，我待会看看
