### ISSUE TITLE
GitHub Action Broken

### ISSUE THREAD

**Issue by imxyy1soope1** [go-musicfox/go-musicfox#194]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

f7cb76f62ca86db99d44f7938e11d7f1446843cd 后 GitHub Action 编译报错。

> NOTE: 可以尝试在编译环境中加入X11支持
> （我也不太懂

### Environment / 运行环境

None

### If applicable, list the error messages you see
如果有错误输出请一并填入

```
  ⨯ release failed after 3m25s                       error=failed to build for linux_amd64_v1: exit status 1: # github.com/robotn/gohook
In file included from ./event/pub.h:20,
                 from ./event/goEvent.h:18,
                 from vendor/github.com/robotn/gohook/hook.go:22:
./event/../hook/x11/input_c.h:19:10: fatal error: X11/keysym.h: No such file or directory
   19 | #include <X11/keysym.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

make: *** [Makefile:47: release-dry-run] Error 1
Error: Process completed with exit code 2.
```

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

None

**Comment by anhoder** [comment]
fixed

**Comment by imxyy1soope1** [comment]
神速
