### ISSUE TITLE
关于将自定义字符改为自定义字符串

### ISSUE THREAD

**Issue by NobodyHere-rrr** [go-musicfox/go-musicfox#197]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

由于NerdFont本身的一些特殊性质，在其后有字符（空格除外）阻挡时，图标会按一定比例缩小，导致看上去很奇怪。
自定义单个字符对于自定义使用NerdFont十分不友好，故希望修改自定义字符为自定义字符串。

有无空格展示：
![swappy-20230929_125252](https://github.com/go-musicfox/go-musicfox/assets/62543054/53e72ebb-8ad6-49b8-a9ac-991d5a5c1d73)
![swappy-20230929_125304](https://github.com/go-musicfox/go-musicfox/assets/62543054/3e469c49-e2d8-4350-8d06-588b7e242c81)

配置文件：
![swappy-20230929_125915](https://github.com/go-musicfox/go-musicfox/assets/62543054/7924c879-5ba2-41c1-8182-6474baa42117)

目前的实际效果：
![swappy-20230929_125947](https://github.com/go-musicfox/go-musicfox/assets/62543054/30c32d5a-0715-48b0-a366-cacd58af26e8)

**Comment by anhoder** [comment]
可以用等宽的nerd font，不等宽的会有问题
