### ISSUE TITLE
macos经常在切歌时闪退

### ISSUE THREAD

**Issue by ZScai** [go-musicfox/go-musicfox#213]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

musicfox在自动或手动切歌时，都要概率发生闪退现象

### Environment / 运行环境

macOS：14.1.1 (23B81)  M2芯片；musicfoc: v4.3.0

### If applicable, list the error messages you see
如果有错误输出请一并填入

92173 segmentation fault  musicfox
<img width="908" alt="image" src="https://github.com/go-musicfox/go-musicfox/assets/86775125/6c9d6b55-ccf4-48ab-b677-18c2e0f3117f">

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by yuzhen1024** [comment]
linux复现，没有任何报错信息，但会显示 加载中 ，然后卡住不动，不得不关掉终端重启。
没有显示 `echo ${MUSICFOX_ROOT}` 目录路径，也没有`~/.go-musicfox/` 的目录。

**Comment by Modolet** [comment]
linux复现，日志如下
```
2024/03/19 11:27:58 [ERROR] Lastfm other err: empty session key
github.com/go-musicfox/go-musicfox/internal/lastfm.(*Client).UpdateNowPlaying
	/go/src/go-musicfox/internal/lastfm/api.go:89
github.com/go-musicfox/go-musicfox/internal/lastfm.Report.func1
	/go/src/go-musicfox/internal/lastfm/api.go:146
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650
```

**Comment by anhoder** [comment]
更新到最新版试试，这个issue先关闭，如果还有问题请重新创建一个issue
