### ISSUE TITLE
退出及退出登录的快捷键调整为仅大写 W

### ISSUE THREAD

**Issue by xtmu** [go-musicfox/go-musicfox#215]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

按 q 退出程序时容易误操作按到 w 退出登录，退出登录基本上不会用到，可否取消小写 w 按键绑定。

**Comment by anhoder** [comment]
[v4.3.2](https://github.com/go-musicfox/go-musicfox/releases/tag/v4.3.2) 已实现
