### ISSUE TITLE
请增加list多少行的config

### ISSUE THREAD

**Issue by stevenfrog** [go-musicfox/go-musicfox#219]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

我在ubuntu下使用你的musicfox, 实在太好了.
因为现在linux已经没有网易云音乐的播放器了, 以前的哪个, 因为api变更, 不能登陆了.

只是现在的显示有点空, 我希望你能增加一个歌曲list那里, 显示多少行的config
现在只是显示5行, 太少了

![Screenshot_2023-12-22_11-11-22](https://github.com/go-musicfox/go-musicfox/assets/1052002/f3797fce-2d2e-47fe-a3eb-9558d5791ae2)

**Comment by stevenfrog** [comment]
如果能通过config调整显示歌词的行数就更好了.
![Screenshot_2024-01-15_11-41-11](https://github.com/go-musicfox/go-musicfox/assets/1052002/fe9334c4-baf3-487a-a9ff-f60fd46106e7)

**Comment by lihaohong6** [comment]
其实还没完成。虽然commit里说修复了，但是还没有同步到musicfox。
