### ISSUE TITLE
自动签到功能疑似导致云贝清空惩罚

### ISSUE THREAD

**Issue by Arcadi4** [go-musicfox/go-musicfox#222]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

最近收到了因为“存在非法获取云贝”而清空云贝的惩罚，申诉无效。用过的第三方软件应该只有Musicfox（12000云贝😥
当然不排除是网易发癫，如果有遇到类似情况的麻烦一同反馈来核实问题。
<img width="319" alt="截屏2023-12-27 15 59 07" src="https://github.com/go-musicfox/go-musicfox/assets/97033226/1a20681b-f620-40bc-8764-370fea22a0a4">

### Environment / 运行环境

MacBook Air 2020
macOS Ventura
Musicfox v4.3.0

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
你这么一说，才发现我也收到通知了🤯

**Comment by Arcadi4** [comment]
@anhoder 那要不要先给这个功能加个开关，默认关闭?🤔

**Comment by anhoder** [comment]
已经有开关了，可以在配置文件中关闭，不过现在默认是开启的
