### ISSUE TITLE
暂停播放时不要占用音频

### ISSUE THREAD

**Issue by yuzhen1024** [go-musicfox/go-musicfox#224]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

暂停播放时不要占用音频

1. 桌面判断有软件正在占用音频，使得桌面无法自动熄屏。（如 [sway-audio-idle-inhibit](https://github.com/ErikReider/SwayAudioIdleInhibit) 。）
2. 蓝牙耳机如果是连接多个设备的那种，那么其中一个设备正在播放音乐将持续占用这个蓝牙耳机。（通常在一个设备停止播放，另一个设备开始播放时，耳机的对设备的焦点会切换。）

**Comment by anhoder** [comment]
底层依赖库(oto)问题
