### ISSUE TITLE
ArchLinux 安装后播放报错

### ISSUE THREAD

**Issue by BarryYangi** [go-musicfox/go-musicfox#225]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

使用pacman安装完成后正常打开空格播放歌曲时报错

### Environment / 运行环境

ArchLinux、Hyprland

### If applicable, list the error messages you see
如果有错误输出请一并填入

2024/02/02 18:47:37 catch panic, err: oto: ALSA error: Operation not supported
failed to initialize speaker
github.com/faiface/beep/speaker.Init
	github.com/faiface/beep@v1.1.0/speaker/speaker.go:42
github.com/go-musicfox/go-musicfox/internal/player.(*beepPlayer).listen
	github.com/go-musicfox/go-musicfox/internal/player/beep_player.go:189
github.com/go-musicfox/go-musicfox/utils.PanicRecoverWrapper
	github.com/go-musicfox/go-musicfox/utils/recover.go:22
runtime.goexit
	runtime/asm_amd64.s:1650, stack: goroutine 6 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/go-musicfox/go-musicfox/utils.Recover(0x0)
	github.com/go-musicfox/go-musicfox/utils/recover.go:10 +0x53
panic({0x5922b5e11060?, 0xc000112030?})
	runtime/panic.go:914 +0x21f
github.com/go-musicfox/go-musicfox/internal/player.(*beepPlayer).listen(0xc00021a240)
	github.com/go-musicfox/go-musicfox/internal/player/beep_player.go:190 +0xe05
github.com/go-musicfox/go-musicfox/utils.PanicRecoverWrapper(0x0?, 0x0?)
	github.com/go-musicfox/go-musicfox/utils/recover.go:22 +0x4f
created by github.com/go-musicfox/go-musicfox/internal/player.NewBeepPlayer in goroutine 1
	github.com/go-musicfox/go-musicfox/internal/player/beep_player.go:64 +0x256

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

> cat musicfox.log
2024/02/02 18:47:33 [ERROR] Lastfm other err: lastfm key或secret为空
github.com/go-musicfox/go-musicfox/internal/lastfm.NewClient
	github.com/go-musicfox/go-musicfox/internal/lastfm/api.go:26
github.com/go-musicfox/go-musicfox/internal/ui.NewNetease
	github.com/go-musicfox/go-musicfox/internal/ui/netease.go:41
github.com/go-musicfox/go-musicfox/internal/commands.runPlayer
	github.com/go-musicfox/go-musicfox/internal/commands/netease.go:44
github.com/gookit/gcli/v2.(*Command).execute
	github.com/gookit/gcli/v2@v2.3.4/cmd.go:243
github.com/gookit/gcli/v2.(*App).doRun
	github.com/gookit/gcli/v2@v2.3.4/app_run.go:173
github.com/gookit/gcli/v2.(*App).Run
	github.com/gookit/gcli/v2@v2.3.4/app_run.go:126
github.com/go-musicfox/go-musicfox/internal/entry.runCLI
	github.com/go-musicfox/go-musicfox/internal/entry/cli.go:53
github.com/go-musicfox/go-musicfox/internal/entry.AppEntry
	github.com/go-musicfox/go-musicfox/internal/entry/entry.go:10
main.main
	./musicfox.go:8
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_amd64.s:1650
2024/02/02 18:47:37 catch panic, err: oto: ALSA error: Operation not supported
failed to initialize speaker
github.com/faiface/beep/speaker.Init
	github.com/faiface/beep@v1.1.0/speaker/speaker.go:42
github.com/go-musicfox/go-musicfox/internal/player.(*beepPlayer).listen
	github.com/go-musicfox/go-musicfox/internal/player/beep_player.go:189
github.com/go-musicfox/go-musicfox/utils.PanicRecoverWrapper
	github.com/go-musicfox/go-musicfox/utils/recover.go:22
runtime.goexit
	runtime/asm_amd64.s:1650, stack: goroutine 6 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/go-musicfox/go-musicfox/utils.Recover(0x0)
	github.com/go-musicfox/go-musicfox/utils/recover.go:10 +0x53
panic({0x5922b5e11060?, 0xc000112030?})
	runtime/panic.go:914 +0x21f
github.com/go-musicfox/go-musicfox/internal/player.(*beepPlayer).listen(0xc00021a240)
	github.com/go-musicfox/go-musicfox/internal/player/beep_player.go:190 +0xe05
github.com/go-musicfox/go-musicfox/utils.PanicRecoverWrapper(0x0?, 0x0?)
	github.com/go-musicfox/go-musicfox/utils/recover.go:22 +0x4f
created by github.com/go-musicfox/go-musicfox/internal/player.NewBeepPlayer in goroutine 1
	github.com/go-musicfox/go-musicfox/internal/player/beep_player.go:64 +0x256

**Comment by Keanu-42** [comment]
So do I. 

- OS: Arch
- Kernel: 6.7.2-arch1-2
- display: X11

**Comment by imxyy1soope1** [comment]
pulseaudio-alsa pipewire-alsa装了没

**Comment by BarryYangi** [comment]
> pulseaudio-alsa pipewire-alsa装了没

装过了

**Comment by anhoder** [comment]
环境问题，安装oto依赖https://github.com/ebitengine/oto#prerequisite
