### ISSUE TITLE
云盘里的音乐无法播放，请求增加跳过功能

### ISSUE THREAD

**Issue by Stealth1412** [go-musicfox/go-musicfox#231]
### Check for existing issues
检查是否已存在相同issue

- [x] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

歌单里存在私人云盘里的音乐，播放到云盘里的音乐就会卡住，只能重启客户端

### Environment / 运行环境

archlinux amd64
v3.7.0

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by Stealth1412** [comment]
不好意思，我现在看到之前关闭的类似的issue了。但还是想说一下遇到歌单里云盘的歌会直接停止播放，能不能让他直接跳过这首歌

**Comment by anhoder** [comment]
目前播放不了会自动跳过，如果连续三首都失败才会暂停
