### ISSUE TITLE
能否添加一个”添加到播放列表“的功能？

### ISSUE THREAD

**Issue by daief** [go-musicfox/go-musicfox#232]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

将当前查看的列表（搜索结果、歌单、专辑）内容追加到当前播放列表，如下图：

![image](https://github.com/go-musicfox/go-musicfox/assets/19222089/ae619aeb-d6dd-4f1a-829b-522b110f0344)

**Comment by imxyy1soope1** [comment]
有的，可以按？键查看按键说明

**Comment by daief** [comment]
> 有的，可以按？键查看按键说明

我只看到把当前选中歌曲追加到列表的操作，没找到追加整个列表的。

**Comment by anhoder** [comment]
Implemented in v4.4.0

type `e`/`E` on a playlist item
