### ISSUE TITLE
apline arm64 tty 播放不了一部分不是vip的歌。错误如下

### ISSUE THREAD

**Issue by gmicroul** [go-musicfox/go-musicfox#237]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

2024/03/01 13:18:08 catch panic, err: oto: ALSA error: Invalid argument
failed to initialize speaker
github.com/faiface/beep/speaker.Init
	/home/user/go-musicfox/vendor/github.com/faiface/beep/speaker/speaker.go:42
github.com/go-musicfox/go-musicfox/internal/player.(*beepPlayer).listen
	/home/user/go-musicfox/internal/player/beep_player.go:189
github.com/go-musicfox/go-musicfox/utils.PanicRecoverWrapper
	/home/user/go-musicfox/utils/recover.go:22
runtime.goexit
	/usr/lib/go/src/runtime/asm_arm64.s:1197, stack: goroutine 19 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x64
github.com/go-musicfox/go-musicfox/utils.Recover(0x0)
	/home/user/go-musicfox/utils/recover.go:10 +0x48
panic({0xa69e60?, 0x40005e07e0?})
	/usr/lib/go/src/runtime/panic.go:914 +0x218
github.com/go-musicfox/go-musicfox/internal/player.(*beepPlayer).listen(0x400023cc60)
	/home/user/go-musicfox/internal/player/beep_player.go:190 +0xc00
github.com/go-musicfox/go-musicfox/utils.PanicRecoverWrapper(0x0?, 0x0?)
	/home/user/go-musicfox/utils/recover.go:22 +0x54
created by github.com/go-musicfox/go-musicfox/internal/player.NewBeepPlayer in goroutine 1
	/home/user/go-musicfox/internal/player/beep_player.go:64 +0x238

### Environment / 运行环境

xiaomi-mido:~$ ./musicfox --version
Musicfox - 命令行版网易云音乐

Version: v4.3.1-4-ga31ceea
        
 ███╗   ███╗ ██╗   ██╗ ███████╗ ██╗  ██████╗ ███████╗  ██████╗  ██╗  ██╗
 ████╗ ████║ ██║   ██║ ██╔════╝ ██║ ██╔════╝ ██╔════╝ ██╔═══██╗ ╚██╗██╔╝
 ██╔████╔██║ ██║   ██║ ███████╗ ██║ ██║      █████╗   ██║   ██║  ╚███╔╝ 
 ██║╚██╔╝██║ ██║   ██║ ╚════██║ ██║ ██║      ██╔══╝   ██║   ██║  ██╔██╗ 
 ██║ ╚═╝ ██║ ╚██████╔╝ ███████║ ██║ ╚██████╗ ██║      ╚██████╔╝ ██╔╝ ██╗
 ╚═╝     ╚═╝  ╚═════╝  ╚══════╝ ╚═╝  ╚═════╝ ╚═╝       ╚═════╝  ╚═╝  ╚═╝
xiaomi-mido:~$ uname -a
Linux xiaomi-mido 6.5.2-postmarketos-qcom-msm8953 #1-postmarketos-qcom-msm8953 SMP PREEMPT Thu Nov 30 21:46:47 UTC aarch64 Linux

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
安装oto依赖https://github.com/ebitengine/oto#prerequisite
