### ISSUE TITLE
切换歌曲会 panic

### ISSUE THREAD

**Issue by zhuxinzzz** [go-musicfox/go-musicfox#238]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

启动大半天之后，切换歌曲。panic 。
错误发生在github.com/anhoder/foxful-cli/model包的(*Main).menuItemView函数中，并且似乎在调用这个函数时导致了崩溃。menuItemView函数调用是在处理或渲染某个菜单项的视图逻辑时发生的，可能存在逻辑错误或不正确的数据导致程序无法继续执行。

复现：目前没办法复现

✗ cat go-musicfox.ini
```ini
# 启动页配置
[startup]
# 是否显示启动页
show=true
# 启动页进度条是否有回弹效果
progressOutBounce=true
# 启动页时长
loadingSeconds=0
# 启动页欢迎语
welcome=musicfox
# 启动时自动签到
signin=false
# 启动时检查更新
checkUpdate=true

# 进度条配置
[progress]
# 进度条已加载字符
fullChar="#"
fullCharWhenFirst="#"
fullCharWhenLast="#"
lastFullChar="#"
# 进度条未加载字符
emptyChar="."
emptyCharWhenFirst="."
emptyCharWhenLast="."
firstEmptyChar="."

# 主页面配置
[main]
# 是否显示标题
showTitle=true
# 加载中提示
loadingText=[加载中...]
# 歌曲音质，standard,higher,exhigh,lossless,hires
songLevel=higher
# 主题颜色
# 随机
# primaryColor=random
# 经典网易云音乐红
#primaryColor="#ea403f"
#primaryColor="#33C5FF"
primaryColor="#71D4F1"
# windows,linux下的通知图标
notifyIcon="logo.png"
# 是否显示歌词
showLyric=true
# 歌词偏移 ms
lyricOffset=0
# 显示歌词翻译
showLyricTrans=false
# 是否显示通知信息
showNotify=false
# 开启pprof, --pprof时会开启
pprofPort=9876
# altScreen显示模式
altScreen=true
# 开启鼠标事件
enableMouseEvent=true
# 双列显示，开启务必使用等宽字体
doubleColumn=true
# 下载目录，默认为${MUSICFOX_ROOT}/download
downloadDir=
# 文件名模板
downloadFileNameTpl={{.SongName}}-{{.ArtistName}}.{{.SongType}}
# 缓存目录，默认为${MUSICFOX_ROOT}/cache
# !!!注意!!! 如果使用mpd,mpd配置中的"music_directory"必须与cacheDir一致
cacheDir=
# 缓存大小（以MB为单位），0为不使用缓存，-1为不限制，默认为0
cacheLimit=-1
# 是否显示歌单下所有歌曲，默认不开启，仅获取歌单前1000首，开启后可能会占用更多内存（大量歌曲数据）和带宽（会同时发送多个请求获取歌单下歌曲数据）
showAllSongsOfPlaylist=false

[global_hotkey]
# 全局快捷键
# 格式：键=功能 (https://github.com/go-musicfox/go-musicfox/blob/master/internal/ui/event_handler.go#L15)
# ctrl+shift+space=toggle

[autoplay]
# 是否开启自动播放，默认不开启
autoPlay=false
# 自动播放歌单，dailyReco, like, name:歌单名, no（保持上次退出时的设置，无视offset），默认为dailyReco
autoPlayList=dailyReco
# 播放偏移，0为第一首，-1为最后一首，默认为0
offset=0
# 播放模式，listLoop, order, singleLoop, random（无视offset）, intelligent（心动）, last（上次退出时的模式），默认为last
playMode=last

[player]
# 播放引擎 beep / mpd(需要安装配置mpd) / osx(Mac才可用)
# 不填Mac默认使用osx，其他系统默认使用beep（推荐的配置）
#engine=beep
# beep使用的mp3解码器，可选：go-mp3, minimp3 (minimp3更少的CPU占用，但是稳定性不如go-mp3)
beepMp3Decoder=go-mp3

# mpd配置
mpdBin=/usr/local/bin/mpd
# !!!注意!!! 一定要在配置文件中设置pid_file，否则在退出时不会kill掉mpd进程
mpdConfigFile=/Users/anhoder/.mpd/mpd.conf
# tcp 或 unix
mpdNetwork=unix
# tcp时填写ip+port(例如:127.0.0.1:1234)，unix时填写socket文件路径
mpdAddr=

[unm]
# UNM开关
switch=true
# UNM源: kuwo,kugou,migu,qq
sources=kuwo,kugou,migu,qq
# UNM搜索其他平台限制 0-3
searchLimit=0
# 解除会员限制
enableLocalVip=true
# 解除音质限制
unlockSoundEffects=true
# QQ音乐cookie文件
qqCookieFile=

```

### Environment / 运行环境

Linux 5.15.77-amd64-desktop        
Musicfox - 命令行版网易云音乐

Version: v4.3.1

### If applicable, list the error messages you see
如果有错误输出请一并填入

/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /go/src/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:465 +0x91
panic({0xb18f60?, 0xc0011a1158?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/anhoder/foxful-cli/model.(*Main).menuItemView(0xc0000f6600, 0x1?, 0x9)
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/main.go:466 +0xa30
github.com/anhoder/foxful-cli/model.(*Main).menuLineView(0xc0000f6600, 0xc000142720, 0x6b?)
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/main.go:397 +0x379
github.com/anhoder/foxful-cli/model.(*Main).menuListView(0xc0000f6600, 0xc000142720, 0xc000e176f0)
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/main.go:355 +0x27b
github.com/anhoder/foxful-cli/model.(*Main).View(0xc0000f6600, 0xc000142720)
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/main.go:184 +0x38f
github.com/anhoder/foxful-cli/model.(*App).View(0xc000142720?)
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/app.go:123 +0x42
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc0000b5ad0, {0xdadaf0?, 0xc000142720?}, 0xc0002b1980?)
        /go/src/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:400 +0x5bc
github.com/charmbracelet/bubbletea.(*Program).Run(0xc0000b5ad0)
        /go/src/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:528 +0x83f
github.com/anhoder/foxful-cli/model.(*App).Run(0xc000142720)
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/app.go:146 +0x27a
github.com/go-musicfox/go-musicfox/internal/commands.runPlayer(0xc0001ce3c0?, {0xc000127480?, 0x0?, 0x0?})
        /go/src/go-musicfox/internal/commands/netease.go:60 +0x498
github.com/gookit/gcli/v2.(*Command).execute(0xc0001ce300, {0xc000127480, 0x0, 0x0})
        /go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/cmd.go:243 +0x10c
github.com/gookit/gcli/v2.(*App).doRun(0xc00021a000, {0xb7305c, 0x7}, {0xc000127480, 0x0, 0x0})
        /go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/app_run.go:173 +0x426
github.com/gookit/gcli/v2.(*App).Run(0xc00021a000)
        /go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/app_run.go:126 +0x2d8
github.com/go-musicfox/go-musicfox/internal/entry.runCLI()
        /go/src/go-musicfox/internal/entry/cli.go:53 +0x3b3
github.com/go-musicfox/go-musicfox/internal/entry.AppEntry()
        /go/src/go-musicfox/internal/entry/entry.go:10 +0x30
main.main()
        /go/src/go-musicfox/cmd/musicfox.go:8 +0xf
        

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
与 #240 重复
