### ISSUE TITLE
中文显示乱码

### ISSUE THREAD

**Issue by cmdblock** [go-musicfox/go-musicfox#239]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

我用的是windows terminal+pwsh, 编码为utf8, 直接输入中文上屏windows terminal没有任何问题。使用musicfox的搜索功能输入中文时候上屏的文字变成了乱码

### Environment / 运行环境

windows系统，
windows terminal+pwsh

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by zhuxinzzz** [comment]
换个终端可能可以解决。

**Comment by anhoder** [comment]
终端问题，更换字符集
