### ISSUE TITLE
能否加一个歌曲列表翻页功能

### ISSUE THREAD

**Issue by PullAndRun** [go-musicfox/go-musicfox#241]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

在歌曲列表按某些键可以翻页。歌曲太多，按住上下键翻页找歌体验不是很好。

**Comment by anhoder** [comment]
https://github.com/go-musicfox/go-musicfox/releases/tag/v4.3.2
