### ISSUE TITLE
Windows System Media Transport Controls 支持

### ISSUE THREAD

**Issue by mokurin000** [go-musicfox/go-musicfox#246]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

windows 10 引入了新的媒体控制协议，SMTC
（目前资源管理器自带的控制很有限，ModernFlyout做的比较完善）

集成之后，用户可以：
使用 Fn 系控制键控制 musicfox
使用 ModernFlyout 控制 musicfox
对接SMTC到其他媒体控制协议（目前没人做，因为连Windows媒体播放器的时间线支持也是半残）

不幸的，由于生态欠缺，要么musicfox自己从winmd bindgen一下Windows.Media.Controls 的东西，要么就只能Cpp/Rust/Python调用现有WinRT库给musicfox用了

**Comment by poly000** [comment]
https://github.com/saltosystems/winrt-go/pull/88

**Comment by mokurin000** [comment]
https://github.com/mokurin000/smtc-go

**Comment by mokurin000** [comment]
https://github.com/waylyrics/winrt-go
SMTC 协议的生包装

**Comment by anhoder** [comment]
Implemented in v4.4.0
