### ISSUE TITLE
作为daemon启动

### ISSUE THREAD

**Issue by glyh** [go-musicfox/go-musicfox#247]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

希望软件可以添加选项允许作为daemon启动，这样前台的gui关了之后还可以在后台播放音乐。

**Comment by glyh** [comment]
如果PR-welcomed 我可以帮忙实现

**Comment by anhoder** [comment]
welcome

**Comment by glyh** [comment]
我阅读过源代码，发现似乎控制音乐的逻辑和UI是混合在一起的。这个功能也许需要重构……

**Comment by glyh** [comment]
Close in favor of https://github.com/go-musicfox/go-musicfox/issues/252
