### ISSUE TITLE
有些歌只能播放一部分，如果有去掉只能播放一部份的歌的开关就好了

### ISSUE THREAD

**Issue by PullAndRun** [go-musicfox/go-musicfox#251]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

https://music.163.com/#/song?id=431259256
比如这个歌只能播放一小段，如果有个开关，能过滤掉这种只能播一小段歌曲就好了。打开开关，这种不完整的歌曲就不会出现在列表里。

**Comment by lihaohong6** [comment]
这个只能播一小段是因为是VIP歌曲吧。

**Comment by haowuge** [comment]
> 这个只能播一小段是因为是VIP歌曲吧。

对对，就是这个意思，跳过VIP曲目

**Comment by PullAndRun** [comment]
unm已恢复。本feature消失。
