### ISSUE TITLE
Refactor TUI

### ISSUE THREAD

**Issue by glyh** [go-musicfox/go-musicfox#252]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

在现有架构下，无论是#248 还是 #247 都无法轻易实现，因为各个模块之间耦合较强。请问如果我帮助重写UI并且采用BubbleTea的严格MVC架构，作者会接受PR吗？

**Comment by anhoder** [comment]
上游库也是自己维护的，加个判断就完了...

不使用bubbletea的render是为了避免全屏刷新，一方面是减少太多无用刷新，另一方面全屏刷新可能会导致一些终端出现闪烁

至于daemon，我觉得更重要的是server和client的通信协议设计，代码只是小头，之前没实现只是我确实没有这个使用场景，引入的代价远大于使用价值

**Comment by glyh** [comment]
但是似乎所有UI相关的功能都可能要改写上游库吧……
