### ISSUE TITLE
歌曲序号是不是从1开始更好（而不是0）

### ISSUE THREAD

**Issue by haowuge** [go-musicfox/go-musicfox#254]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

歌曲序号是不是从1开始更好（而不是0），从0开始是计算机的逻辑，针对用户应该替换成1？谢谢

**Comment by anhoder** [comment]
1. 用户基本是程序员或计算机相关人员，从0开始基本没有理解障碍 （类似hello world?）
2. 从1开始的话，第一页的10、第十页的100会和当前页位数不一致，显示上不协调
