### ISSUE TITLE
[BUG]使用musicfox听歌后听歌记录会被显示为24小时

### ISSUE THREAD

**Issue by GrassBlock1** [go-musicfox/go-musicfox#256]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

无论配置中是否开启自动签到，在使用musicfox时一首歌播放完毕后，客户端“听歌足迹”均会显示今日听歌时长为24小时（但总时长不变），但第二天似乎会自动恢复当天听歌时长为正确的时长。

未播放时：
![Screenshot_2024-05-06-14-05-45-040_com netease cloudmusic](https://github.com/go-musicfox/go-musicfox/assets/46253950/12550813-fc36-42fb-b9ed-bf34489ab985)
播放后：
![Screenshot_2024-05-06-14-12-30-246_com netease cloudmusic](https://github.com/go-musicfox/go-musicfox/assets/46253950/64183d38-9abf-4fe1-bef2-9de47b428b74)

### Environment / 运行环境

Arch Linux x86_64
musicfox 版本  4.3.3

### If applicable, list the error messages you see
如果有错误输出请一并填入

none

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

none

**Comment by anhoder** [comment]
已修复24小时问题，不过现在的上报好像不太行了，都被网易云过滤了

**Comment by GrassBlock1** [comment]
> 已修复24小时问题，不过现在的上报好像不太行了，都被网易云过滤了

感谢。
上报在我这边似乎没有问题，听歌时长会正常增加。

**Comment by UApocalypse** [comment]
确实，听歌记录都被过滤完了
