### ISSUE TITLE
建议增加「心动模式」

### ISSUE THREAD

**Issue by sunwgit** [go-musicfox/go-musicfox#264]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

---
###  和每日推荐一样，单独列一个条目
 
 
![Screenshot_20240518-194455](https://github.com/go-musicfox/go-musicfox/assets/11364780/ae6a9329-a7e9-482b-a9d2-697b9046596c)

---
### 在播放单曲时，播放模式中有一个心动模式

![Screenshot_20240518-194422](https://github.com/go-musicfox/go-musicfox/assets/11364780/2b817412-a045-429d-a84e-280ed7ec9951)

**Comment by imxyy1soope1** [comment]
第二种心动模式已存在，按大写P开启

**Comment by anhoder** [comment]
可以直接使用现有入口：进入「我喜欢的歌单」，按大写p开启
