### ISSUE TITLE
单曲播放模式「心动模式」(快捷键P)无效

### ISSUE THREAD

**Issue by sunwgit** [go-musicfox/go-musicfox#265]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

https://github.com/go-musicfox/go-musicfox/issues/264#issuecomment-2118845858 提到说单曲播放的播放模式中已存在「心动模式」

但我试了下，在播放时按下大写P没有任何变化。
查看了日志，没有任何反馈。

### Environment / 运行环境

- OS：macos ventura 13.6.7
- CPU:   Intel
- musicfox: 4.4.1

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
跟网易云一样，仅在`我喜欢的音乐`里才能用

另外，同一个功能在一个issue里讨论就好了，这个先关了
