### ISSUE TITLE
播放歌曲信息残留

### ISSUE THREAD

**Issue by 663D74N** [go-musicfox/go-musicfox#271]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

播放信息残留 ，试过按 R 无效

### Environment / 运行环境

版本	Windows 10 专业工作站版
版本号	22H2
操作系统内部版本	19045.4412
体验	Windows Feature Experience Pack 1000.19056.1000.0

![vaJNbJJ83G](https://github.com/go-musicfox/go-musicfox/assets/13313477/a448c786-e76d-4b27-8bd4-9803b643920b)

----
[musicfox.log](https://github.com/go-musicfox/go-musicfox/files/15410749/musicfox.log)

**Comment by anhoder** [comment]
换Windows Terminal, 不要用cmd（太垃圾了）
