### ISSUE TITLE
下载歌名带星号的曲子出错

### ISSUE THREAD

**Issue by hak0** [go-musicfox/go-musicfox#274]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

一般在使用快捷键d下载歌曲时，下载位置是%appdata%/go-musicfox/download

但是当歌名带星号时，歌曲出现在%temp%下，文件名异常，且缺少mp3tag信息

例子：下载歌曲`MELT*DOWN (feat. Matatabi Sound System, DJ NECOJITA, Shinonome Interface & blaxervant) [HVS ver.]`
文件出现在temp目录下，且文件名为MELT**185578907**DOWN (feat. Matatabi Sound System, DJ NECOJITA, Shinonome Interface &amp; blaxervant) [HVS ver.]-Kobaryo,Matatabi Sound System,DJ NECOJITA,Shinonome Interface,blaxervant.mp3

多次下载时出现多个文件，且文件名中替代星号的数字每次都不一样

### Environment / 运行环境

系统版本: Windows 11 23H2 x64
musicfox 版本: v4.4.1

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
fixed ([v4.5.0](https://github.com/go-musicfox/go-musicfox/releases/tag/v4.5.0))
