### ISSUE TITLE
添加博客功能

### ISSUE THREAD

**Issue by PixelSkider** [go-musicfox/go-musicfox#294]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

添加听书博客功能

**Comment by anhoder** [comment]
你想要的是这个？

![image](https://github.com/go-musicfox/go-musicfox/assets/27605589/8eade9ee-c331-496b-906c-03564f4e56bf)

**Comment by PixelSkider** [comment]
> 你想要的是这个？
> 
> ![image](https://github.com/go-musicfox/go-musicfox/assets/27605589/8eade9ee-c331-496b-906c-03564f4e56bf)
> 

nb
