### ISSUE TITLE
连续出现多首 VIP 试听音乐时无法自动跳过到可播放的免费音乐

### ISSUE THREAD

**Issue by 4285f4** [go-musicfox/go-musicfox#300]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

- 当前播放音乐是免费歌曲，播放完毕时假如接下来的歌曲连续三首及以上都是 VIP 试听歌曲时，将无法自动跳过到下一首可播放的免费歌曲。
- 并且当鼠标不移动到终端窗口内部时，当前播放歌曲也不会切换，光标移入瞬间会切换，但播放时长会停留在之前播放的免费音乐结尾
- 测试歌单：https://music.163.com/playlist?id=12266436537&userid=99359309

![image](https://github.com/go-musicfox/go-musicfox/assets/36158676/e59ffc93-e691-45fc-b956-2d1405cac110)

### Environment / 运行环境

操作系统：Windows 11 23H2 专业版
CPU：x64
MusicFox 版本：4.5.3
运行环境：Windows Terminal

### If applicable, list the error messages you see
如果有错误输出请一并填入

无

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

[musicfox.log](https://github.com/user-attachments/files/16104152/musicfox.log)

**Comment by imxyy1soope1** [comment]
可通过设置`[player]`下的`maxPlayErrCount`修改重试次数

**Comment by 4285f4** [comment]
> 可通过设置`[player]`下的`maxPlayErrCount`修改重试次数

加了一行 `maxPlayErrCount=10` 也不行，还是会停在第三首 VIP 音乐那里

**Comment by anhoder** [comment]
使用新版本 [v4.5.4](https://github.com/go-musicfox/go-musicfox/releases/tag/v4.5.4)
