### ISSUE TITLE
随机模式上一曲逻辑异常

### ISSUE THREAD

**Issue by tdccj** [go-musicfox/go-musicfox#301]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

歌单中使用随机模式切换上一首仍会获得随机的结果，
如：随机歌曲B 的上一首不会是 随机歌曲A 而是新的随机歌曲C。
如此，上一首功能在随机模式下便失去了作用，这是否符合预期？

### Environment / 运行环境

Windows11 x86-64
musicfox v4.5.3

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by imxyy1soope1** [comment]
@anhoder 建议在进入随机模式时生成随机歌曲序列，或使用链表维护歌曲顺序
