### ISSUE TITLE
关于在全局下的操作

### ISSUE THREAD

**Issue by sakuko-1363** [go-musicfox/go-musicfox#302]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

能否不选中软件窗口的情况下进行歌曲的播放暂停切换
大佬能否考虑一下谢谢

**Comment by anhoder** [comment]
参考这个，默认不设置全局快捷键
![CleanShot 2024-07-13 at 21 22 04@2x](https://github.com/user-attachments/assets/e4c4e2a4-0025-4503-aea4-35d83093e045)
