### ISSUE TITLE
[功能建议] 支持kitten或者iterm2协议显示图片

### ISSUE THREAD

**Issue by inkfin** [go-musicfox/go-musicfox#312]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

部分终端如 kitty (unix) 和 iterm2 (macos) 支持终端图片显示协议，windows 平台虽然不支持终端图片协议，但是仍然能通过 chafa 转成 ANSI/Unicode 字符显示。是否可以添加可选功能开关，在播放页面显示图片？

目前播放页面歌单有两行，可以把图片显示在右半边区域

**Comment by imxyy1soope1** [comment]
不是特别有必要，musicfox已经实现三个平台的媒体控制，如在Linux可以使用支持mpris的软件实现歌词、专辑封面等的显示

例：[Waybar](https://github.com/Alexays/Waybar) mpris控件实现播放控制，[SwayNotificationCenter](https://github.com/ErikReider/SwayNotificationCenter) mpris控件实现专辑图片显示和播放控制

![图片](https://github.com/user-attachments/assets/4b52e66f-a5ca-4eb1-a272-bab4ff3a8cfe)

**Comment by inkfin** [comment]
媒体控制实现是已经实现的很好了，非常棒👍。

不过这里说的是另外一个功能，在 terminalUI 中加入图片的显示，有些类似于![nvim 中显示图片](https://github.com/3rd/image.nvim)，是为了让 tui 这部分的功能更加全面。

这应该是一个很有意思的功能，尤其在图片显示逐渐成为新 terminal 标准的当下 （![windows 平台 windows terminal preview 加入](https://github.com/microsoft/terminal/issues/17391)），感兴趣的同学可以留意一下这项技术的发展。

**Comment by imxyy1soope1** [comment]
详见上游库 charmbracelet/bubbletea#163

**Comment by anhoder** [comment]
终端显示图片暂时没有计划
