### ISSUE TITLE
支持暂停心动模式的歌曲

### ISSUE THREAD

**Issue by leihaojun** [go-musicfox/go-musicfox#313]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

目前在心动模式放歌不支持暂停 ， 一按空格就会自动切换到普通模式放列表里的歌。能否支持一下在心动模式按下空格暂停的是心动模式的歌曲？

**Comment by anhoder** [comment]
返回到非歌曲页

**Comment by leihaojun** [comment]
> 返回到非歌曲页

这个逻辑是否有点绕了，要进入到行动模式要向切换进歌曲页，要正常使用心动模式又得切出去歌曲页。直接不进入歌曲也也能进入心动模式是否更好点？
