### ISSUE TITLE
Ubuntu 24.04 下因缺少 libFLAC.so.8 依赖 无法启动

### ISSUE THREAD

**Issue by gapplef** [go-musicfox/go-musicfox#314]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

终端运行

### Environment / 运行环境

Ubuntu 24.04 X86_64
musicfox 4.5.3

### If applicable, list the error messages you see
如果有错误输出请一并填入

musicfox: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory
Ubuntu 24.04软件库中 flac 版本为1.4.3，提供libFLAC.so.12
相关问题 https://github.com/go-musicfox/go-musicfox/pull/97

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
把libFLAC.so.12软链为libFLAC.so.8

**Comment by snowdream** [comment]
对于 Arm64的 Ubuntu、Debian，需要这么做。
ln -s /usr/lib/aarch64-linux-gnu/libFLAC.so.12.0.0 /usr/lib/aarch64-linux-gnu/libFLAC.so.8 
ln -s  /usr/lib/aarch64-linux-gnu/libFLAC.so.12.0.0 /usr/lib/aarch64-linux-gnu/libFLAC.so.8.0.0

对于其他架构的Ubuntu、Debian，aarch64-linux-gnu 可能是其他的字段。
具体参考这里：
https://packages.debian.org/bookworm/libflac12
https://packages.debian.org/bookworm/amd64/libflac12/filelist

**Comment by EntropyGenerator** [comment]
For x86_64 Debian13, you can fix this by
```bash
cd /usr/lib/x86_64-linux-gnu
sudo ln -s libFLAC.so.12 libFLAC.so.8
```

**Comment by chisaato** [comment]
再提供一个思路,可以用patchelf修改依赖的具体文件名
```
patchelf --replace-needed libFLAC.so.8 libFLAC.so.12 musicfox
```

**Comment by PrayRayleigh** [comment]
For x86_64 Debian13, you can fix this by 
cd /usr/lib/x86_64-linux-gnu
sudo ln -s libFLAC.so.12 libFLAC.so.8 or sudo ln -s libFLAC.so.14 libFLAC.so.8

**Comment by SteveZMTstudios** [comment]
或者安装libflac14也可解决问题
