### ISSUE TITLE
mpd播放网易云音乐时不显示title信息问题反馈

### ISSUE THREAD

**Issue by Awkee** [go-musicfox/go-musicfox#315]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

我在i3wm+polybar下面配置go-musicfox播放音乐时mpd显示 title 信息，发现了一个奇怪的现象

> title显示的都是url链接中的文件名（类似: kaljfldfdlfofdf.mp3， 对应url类似 https://xxxx.com/path/to/kaljfldfdlfofdf.mp3) ，而音乐名tag信息并没有正确的显示。

解决方法：
仅仅增加一点**延迟**设置tag就解决了，修改文件`internal/player/mpd_player.go`，对比差异如下：
```bash
diff --git a/internal/player/mpd_player.go b/internal/player/mpd_player.go
index f817069..0333c4d 100644
--- a/internal/player/mpd_player.go
+++ b/internal/player/mpd_player.go
@@ -243,6 +243,8 @@ func (p *mpdPlayer) listen() {
                        err = p.client().PlayID(p.curSongId)
                        mpdErrorHandler(err, false)
                        if !isLocal {
+                               // add 0.5 seconds wait to write  tags
+                               time.Sleep(time.Millisecond * 500)
                                // Doing this because github.com/fhs/gompd/v2/mpd hasn't implement "addtagid" yet
                                command := "addtagid %d %s %s"
                                err = p.client().Command(command, p.curSongId, "artist", p.curMusic.ArtistName()).OK()
```
> 因为没有详细看过本项目代码，不确定是否有更合理的方法。

**修改前效果**
![图片](https://github.com/user-attachments/assets/da3abba7-578d-43c1-8ee8-87bbecc684db)

**修改后效果**
![polybar显示效果](https://github.com/user-attachments/assets/e223adcb-f56c-439f-af92-19a67414ebd3)

### Environment / 运行环境

- arch linux
- x86_64

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

time=2024-08-31T23:28:38.769+08:00 level=INFO source=/apps/code/go/src/github.com/go-musicfox/go-musicfox/internal/ui/player.go:462 msg="Start play song" url=http://m8.music.126.net/20240831235338/e2af6410751545ceacb79ba23f76c243/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3037481081/16a3/74bb/dbef/beafcc1a908c5990ed5b53275d61d284.mp3 type=mp3 song="{Id:3405868 Name:Scarborough Fair Duration:4m10.961s Artists:[{Id:74618 Name:Sarah Brightman}] Album:{Id:345234 Name:The Very Best of Sarah Brightman 1990-2000 PicUrl:http://p2.music.126.net/GyywegDyasFj_KAgps7VIg==/789449348785243.jpg Artists:[]} Title:Scarborough Fair}"

**Comment by imxyy1soope1** [comment]
无法复现，请提供详细复现步骤
