### ISSUE TITLE
 go-musicfox : 依赖: flac 但是它将不会被安装                依赖: libasound2-dev 但是它将不会被安装

### ISSUE THREAD

**Issue by snowdream** [go-musicfox/go-musicfox#316]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

 go-musicfox : 依赖: flac 但是它将不会被安装
               依赖: libasound2-dev 但是它将不会被安装

### Environment / 运行环境

树莓派 Debian

### If applicable, list the error messages you see
如果有错误输出请一并填入

 go-musicfox : 依赖: flac 但是它将不会被安装
               依赖: libasound2-dev 但是它将不会被安装

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by snowdream** [comment]
解决方案1：
```
sudo apt-get install -y libasound2-dev flac go-musicfox
```


解决方案2：

1. 安装依赖
```
sudo apt-get instlall -y libasound2-dev flac go-musicfox
```

2. 下载对应的安装包
```
wget -c https://github.com/go-musicfox/go-musicfox/releases/download/v4.5.3/go-musicfox_4.5.3_linux_arm64.deb
```

3. 安装
```
sudo dpkg -i go-musicfox_4.5.3_linux_arm64.deb

```

**Comment by snowdream** [comment]
最后可能还要解决这个问题：
https://github.com/go-musicfox/go-musicfox/issues/314#issuecomment-2325466157

**Comment by YanMH996** [comment]
fedora需要安装libsoundio
sudo dnf install  libsoundio
