### ISSUE TITLE
Windows可以实现桌面歌词吗？

### ISSUE THREAD

**Issue by Stevenenenen** [go-musicfox/go-musicfox#320]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the feature
描述你的新功能

看到了Mac版的，觉得这个功能还蛮需要的，可惜不用Mac。有实现的方法吗，或者后续会更新/接入现有歌词插件吗？

**Comment by anhoder** [comment]
可以看看[这个](https://github.com/SmileYik/lyric-for-musicfox)

**Comment by Stevenenenen** [comment]
> 可以看看[这个](https://github.com/SmileYik/lyric-for-musicfox)

我去看看，谢谢
