### ISSUE TITLE
播放记录未能正确上报

### ISSUE THREAD

**Issue by slqy123** [go-musicfox/go-musicfox#321]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

歌曲播放结束后，最近播放歌曲未能更新。

抓包得到歌曲切换时客户端发送了如下请求。日志也没有异常之处。
![image](https://github.com/user-attachments/assets/4300c8d4-bc88-41e0-ada3-0f4a60137bd9)

不知道是不是所有人都这样，我尝试过清空缓存重新登录，并没有效果。

BTW，网易云的web端可以正常更新。似乎web端在切换歌曲时发送的`weblog` 请求数并不一样，不知道是否和这个有关。
![image](https://github.com/user-attachments/assets/88453f5c-c483-4be3-976a-e9c65f3c0794)

### Environment / 运行环境

Musicfox Version: v4.5.3-23-gd7118ac
OS: Arch Linux x86_64
Kernel: Linux 6.11.3-arch1-1

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
已知问题，上报可能会网易云被风控，暂无计划处理
