### ISSUE TITLE
在最新的Mint(基于ubuntu24.04）中无法运行

### ISSUE THREAD

**Issue by yuta-sakata** [go-musicfox/go-musicfox#344]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

安装好后无法运行，依赖无法解决

### Environment / 运行环境

![QQ20241221-104130](https://github.com/user-attachments/assets/8ab98b50-a372-4ae2-a0ba-b9a77380f24c)

### If applicable, list the error messages you see
如果有错误输出请一并填入

musicfox: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by lihaohong6** [comment]
应该是和 #314 一样的问题？

**Comment by yuta-sakata** [comment]
> 应该是和 #314 一样的问题？

没错，非常感谢，我解决了
