### ISSUE TITLE
在播放音乐的时候无法使用耳机播放

### ISSUE THREAD

**Issue by tshangdsun1208** [go-musicfox/go-musicfox#348]
播放音乐的时候，默认选择的设备是电脑的扬声器，而耳机无法播放
软件版本：4.6.0
操作系统：Arch Linux

**Comment by AMIRIOX** [comment]
可能是 [#59](https://github.com/go-musicfox/go-musicfox/issues/59)

pulseaudio 就装`pulseaudio-alsa`， pipewire 就装`pipewire-alsa`
