### ISSUE TITLE
我喜欢的音乐歌单无法显示第1000首以前的歌曲

### ISSUE THREAD

**Issue by ALisstry** [go-musicfox/go-musicfox#349]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

![image](https://github.com/user-attachments/assets/a247e744-0ff6-404a-927c-365fe655a14c)

![image](https://github.com/user-attachments/assets/3250d711-e748-43b0-92a3-6fc0c3147bb3)

如图所示，只需要收藏超过1000首歌，往下翻页到序号999后就翻不动了

### Environment / 运行环境

系统：Win10
处理器：5800H
运行环境：Windows Terminal

### If applicable, list the error messages you see
如果有错误输出请一并填入

_No response_

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by lihaohong6** [comment]
改一下设置文件就行：`showAllSongsOfPlaylist=true`
![image](https://github.com/user-attachments/assets/8021bb1a-bc70-44e7-9d29-d02c8dba99e8)

**Comment by ALisstry** [comment]
好的，谢谢帮助，是我没有检查设置
