### ISSUE TITLE
能否在播放界面歌曲名称旁边显示一个爱心图标?

### ISSUE THREAD

**Issue by touchmii** [go-musicfox/go-musicfox#58]
可以把真正播放中的歌曲喜欢状态显示出来吗?

**Comment by anhoder** [comment]
应该可以，看下网易云接口有木有返回

**Comment by touchmii** [comment]
> 应该可以，看下网易云接口有木有返回

网页版好像没有点红心的功能,只有添加到播放列表的选项,可能要获取一次喜欢歌曲的列表缓存起来,再判断歌曲是否被点了红心.

**Comment by anhoder** [comment]
4.0.0已实现
