### ISSUE TITLE
接入外置音频无声音

### ISSUE THREAD

**Issue by yuzhen1024** [go-musicfox/go-musicfox#59]
播放时仍旧使用内置音频。

**Comment by anhoder** [comment]
具体什么系统和场景

**Comment by yuzhen1024** [comment]
> 具体什么系统和场景

arch linux
目前发现所有非默认音频都出现这种情况，蓝牙耳机或USB连接的音频设备。
musicfox version: v3.7.2

**Comment by anhoder** [comment]
没有设备复现，会不会是系统音频驱动问题

**Comment by yuzhen1024** [comment]
> 没有设备复现，会不会是系统音频驱动问题

至少其它软件播放音频是没有问题的，有Debug的方式吗？

**Comment by yuzhen1024** [comment]
> 没什么很好的办法....
> 
> 底层用的是beep播放音频，你可以把它的demo拉下来跑下，看是不是beep的原因

beep 使用了 [oto](https://github.com/hajimehoshi/oto)，而oto使用 ALSA

[`pacman -S pulseaudio-alsa`](https://wiki.archlinuxcn.org/wiki/PulseAudio#ALSA)
