### ISSUE TITLE
macOS会出现无效播放

### ISSUE THREAD

**Issue by sirlaurie** [go-musicfox/go-musicfox#65]
macOS 13.2.1
iterm 3.5
musicfox 3.7.5

如下图, 程序显示正在播放, 但实际上没有声音, 而且播放进度条已经超过歌曲实际时长.切换其他歌曲歌单也都是这样. 退出重新运行依然无法播放
<img width="738" alt="Screenshot 2023-03-20 at 13 35 12" src="https://user-images.githubusercontent.com/8928155/226255575-83e45f73-56de-402b-8cb1-ac34bf33dc67.png">

**Comment by anhoder** [comment]
m1没出现过，是不是改过配置，贴下内容看看

**Comment by sirlaurie** [comment]
> m1没出现过，是不是改过配置，贴下内容看看

(电脑在公司, 没法贴配置了)音质改到了最高一档, 其他都是默认的.

**Comment by anhoder** [comment]
可能是网速问题，网速不太好还是建议把音质填低

**Comment by sirlaurie** [comment]
> 可能是网速问题，网速不太好还是建议把音质调低

确实是公司网络质量太差了.
