### ISSUE TITLE
m1芯片的消息通知的图片有问题

### ISSUE THREAD

**Issue by xujingkai** [go-musicfox/go-musicfox#66]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/14089362/226295138-f4ee8d18-45a7-4107-bb11-d326eafaffc2.png">
如上图，有个禁止图标

**Comment by anhoder** [comment]
mac系统问题，参考 => https://v2ex.com/t/820968

**Comment by xujingkai** [comment]
> mac系统问题，参考 => https://v2ex.com/t/820968

重启解决了。多谢大佬
