### ISSUE TITLE
播放个人歌单时报错,遇到过好几次,这是解析歌词时间的问题吗,其它几次的错误我没有留意.

### ISSUE THREAD

**Issue by touchmii** [go-musicfox/go-musicfox#74]
panic: runtime error: slice bounds out of range [:-1]usicfox ───────────────────────────────────────────────────

goroutine 27153 [running]:
github.com/go-musicfox/go-musicfox/pkg/lyric.parseLRCTime({0x140004c7aca, 0x2d}, {0x102ec982c?, 0x102c15278?}, {0x102ec9830, 0x1})        当前播放列表 [更新于2023-03-23 17:26:14]　　　　　　　　　
        /go/src/go-musicfox/pkg/lyric/lrc.go:142 +0x214
github.com/go-musicfox/go-musicfox/pkg/lyric.readLRCLine({0x140004c7ac0?, 0x140002d82cb?}, 0x37?)
        /go/src/go-musicfox/pkg/lyric/lrc.go:102 +0x1b8》第一期ED  => 171. Thunder [Alexandros]
github.com/go-musicfox/go-musicfox/pkg/lyric.ReadLRC({0x10301f3a8?, 0x140000b4fa0?})頃のキミへ~ 當山みれい
        /go/src/go-musicfox/pkg/lyric/lrc.go:53 +0xd4                 175. 隔烟水（Cover 晃儿） 特曼,玄觞
github.com/go-musicfox/go-musicfox/pkg/lyric.ReadTranslateLRC({0x10301f3a8?, 0x140000b4fa0?}) 迟（Cover 君ノ
        /go/src/go-musicfox/pkg/lyric/lrc.go:74 +0x28Hanser)（Cove    179. ひとひらの 初音ミク,のりP
github.com/go-musicfox/go-musicfox/pkg/ui.(*Player).updateLyric(0x14000082680, 0x0?)
        /go/src/go-musicfox/pkg/ui/player.go:639 +0x308
created by github.com/go-musicfox/go-musicfox/pkg/ui.(*Player).PlaySong )
        /go/src/go-musicfox/pkg/ui/player.go:418 +0x248

重新打开软件查看播放列表

 => 170. 告白文案《当我嫁给处女座》第一期ED     171. Thunder [Alexandros]
       172. 【中日双语】幻化成风（翻自 梁静茹/     173. 願い~あの頃のキミへ~ 當山みれい
       174. 多幸运 菟菟彩                          175. 隔烟水（Cover 晃儿） 特曼,玄觞
       176. 阴阳名仕录 少恭,白止,肥皂菌,Hanser     177. 【魔道祖师/薛晓】栖迟（Cover 君ノ
       178. ACUTE 中文翻唱(YUKIri&Hanser)（Cove    179. ひとひらの 初音ミク,のりP

播放到 【中日双语】幻化成风（翻自 梁静茹/辻亚弥乃） 拉面儿  这一首马上闪退.
这首歌只能搜索到一个结果,歌词返回如下

```json
{
  "sgc": false,
  "sfy": false,
  "qfy": false,
  "transUser": {
    "id": 116281,
    "status": 99,
    "demand": 0,
    "userid": 310938997,
    "nickname": "月饼只想吃月饼",
    "uptime": 1498708143789
  },
  "lyricUser": {
    "id": 116280,
    "status": 99,
    "demand": 0,
    "userid": 310938997,
    "nickname": "月饼只想吃月饼",
    "uptime": 1498708143789
  },
  "lrc": {
    "version": 20,
    "lyric": "[00:00.000] 作词 : 辻亚弥乃\n[00:00.045] 作曲 : 辻亚弥乃\n[00:00.90]日本語\n[00:08.43]忘れていた目を閉じて 取り戻せ 恋のうた\n[00:15.49]青空に隠れている 手を伸ばしてもう一度\n[00:23.06]忘れないで すぐそばに僕がいる いつの日も\n[00:30.06]星空を眺めている　一人きりの夜明けも\n[00:37.69]たった一つの心 悲しみに暮れないで\n[00:45.05]君のためいきなんて 春風に変えてやる\n[00:52.42]陽のあたる坂道を 自転車で駆けのぼる\n[01:00.28]君と失くした想い出乗せて行くよ\n[01:07.05]ラララララ 口ずさむ くちびるを染めて行く\n[01:15.19]君と見つけたしあわせ花のように\n[01:22.54]中文\n[01:24.31]还记得那场音乐会的烟火\n[01:27.64]还记得那个凉凉的深秋\n[01:31.38]还记得人潮把你推向了我\n[01:34.92]游乐园拥挤的正是时候\n[01:38.70]一个夜晚坚持不睡的等候\n[01:42.48]一起泡温泉奢侈的享受\n[01:45.87]有一次日记里愚蠢的困惑\n[01:49.76]因为你的微笑幻化成风\n[01:53.34]你大大的勇敢保护着我\n[01:57.17]我小小的关怀喋喋不休\n[02:00.81]感谢我们一起走了那么久\n[02:04.39]又再一次回到凉凉深秋\n[02:07.97]给你我的手\n[02:09.96]像温柔野兽\n[02:11.71]我们一直就这样向前走\n[02:15.89]我们小手拉大手\n[02:18.22]一起郊游\n[02:19.97]今天别想太多\n[02:22.80]你是我的梦\n[02:24.64]像北方的风\n[02:26.49]吹着南方暖洋洋的哀愁\n[02:30.57]我们小手拉大手\n[02:32.96]今天加油向昨天挥挥手\n[02:45.26]LA LA LA LA LA LA LA LA~\n[02:57.65]陽のあたる坂道を 自転車で駆けのぼる\n[03:05.46]君と誓った約束乗せて行くよ\n[03:12.28]LA LA LA LA LA~\n[03:13.97]像北方的风\n[03:16.13]吹着南方暖洋洋的哀愁\n[03:20.29]我们小手拉大手\n[03:22.68]今天加油向昨天挥挥手\n[03:27.56]我们小手拉大手\n[03:29.79]今天为我加油\n[03:31.54]舍不得挥挥手\n"
  },
  "klyric": {
    "version": 0,
    "lyric": ""
  },
  "tlyric": {
    "version": 12,
    "lyric": "[by:你所不认识的树怪]\n[00:00.90]日语\n[00:08.43]合上一直忘记闭住的双眼，再一次伸出双手\n[00:15.49]找回隐藏在蓝天中的爱恋之歌\n[00:23.06]一定不要忘记，随时陪伴在你身边的时光\n[00:30.06]望着星空，独自一人的黎明\n[00:37.69]唯一的一颗心，请不要在悲伤中度过\n[00:45.05]就连你的叹息，我也要将它化作春风\n[00:52.42]在洒满阳光的坡道上，骑着自行车\n[01:00.28]载着你和那些遗忘了的记忆奔向远方\n[01:07.05]啦啦啦啦啦，染红嘴唇，轻声吟唱着\n[01:15.19]和你一起找到的幸福，就像花儿一样\n[01:22.54]\n[01:24.31]\n[01:27.64]\n[01:31.38]\n[01:34.92]\n[01:38.70]\n[01:42.48]\n[01:45.87]\n[01:49.76]\n[01:53.34]\n[01:57.17]\n[02:00.81]\n[02:04.39]\n[02:07.97]\n[02:09.96]\n[02:11.71]\n[02:15.89]\n[02:18.22]\n[02:19.97]\n[02:22.80]\n[02:24.64]\n[02:26.49]\n[02:30.57]\n[02:32.96]\n[02:45.26]\n[02:57.65]在洒满阳光的坡道上，骑着自行车\n[03:05.46]载着和你一起约定的誓言去到远方\n[03:12.28]\n[03:13.97]\n[03:16.13]\n[03:20.29]\n[03:22.68]\n[03:27.56]\n[03:29.79]\n[03:31.54]\n"
  },
  "romalrc": {
    "version": 0,
    "lyric": ""
  },
  "code": 200
}

```

未格式化的raw数据

HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: X-Requested-With,Content-Type
Access-Control-Allow-Methods: PUT,POST,GET,DELETE,OPTIONS
Content-Type: application/json; charset=utf-8
Content-Length: 3629
ETag: W/"e2d-mYtMMmBk3skIBhYnz0EpoT7UgtY"
cache-control: max-age=120
Date: Sat, 25 Mar 2023 08:15:16 GMT
Connection: close

{"sgc":false,"sfy":false,"qfy":false,"transUser":{"id":116281,"status":99,"demand":0,"userid":310938997,"nickname":"月饼只想吃月饼","uptime":1498708143789},"lyricUser":{"id":116280,"status":99,"demand":0,"userid":310938997,"nickname":"月饼只想吃月饼","uptime":1498708143789},"lrc":{"version":20,"lyric":"[00:00.000] 作词 : 辻亚弥乃\n[00:00.045] 作曲 : 辻亚弥乃\n[00:00.90]日本語\n[00:08.43]忘れていた目を閉じて 取り戻せ 恋のうた\n[00:15.49]青空に隠れている 手を伸ばしてもう一度\n[00:23.06]忘れないで すぐそばに僕がいる いつの日も\n[00:30.06]星空を眺めている　一人きりの夜明けも\n[00:37.69]たった一つの心 悲しみに暮れないで\n[00:45.05]君のためいきなんて 春風に変えてやる\n[00:52.42]陽のあたる坂道を 自転車で駆けのぼる\n[01:00.28]君と失くした想い出乗せて行くよ\n[01:07.05]ラララララ 口ずさむ くちびるを染めて行く\n[01:15.19]君と見つけたしあわせ花のように\n[01:22.54]中文\n[01:24.31]还记得那场音乐会的烟火\n[01:27.64]还记得那个凉凉的深秋\n[01:31.38]还记得人潮把你推向了我\n[01:34.92]游乐园拥挤的正是时候\n[01:38.70]一个夜晚坚持不睡的等候\n[01:42.48]一起泡温泉奢侈的享受\n[01:45.87]有一次日记里愚蠢的困惑\n[01:49.76]因为你的微笑幻化成风\n[01:53.34]你大大的勇敢保护着我\n[01:57.17]我小小的关怀喋喋不休\n[02:00.81]感谢我们一起走了那么久\n[02:04.39]又再一次回到凉凉深秋\n[02:07.97]给你我的手\n[02:09.96]像温柔野兽\n[02:11.71]我们一直就这样向前走\n[02:15.89]我们小手拉大手\n[02:18.22]一起郊游\n[02:19.97]今天别想太多\n[02:22.80]你是我的梦\n[02:24.64]像北方的风\n[02:26.49]吹着南方暖洋洋的哀愁\n[02:30.57]我们小手拉大手\n[02:32.96]今天加油向昨天挥挥手\n[02:45.26]LA LA LA LA LA LA LA LA~\n[02:57.65]陽のあたる坂道を 自転車で駆けのぼる\n[03:05.46]君と誓った約束乗せて行くよ\n[03:12.28]LA LA LA LA LA~\n[03:13.97]像北方的风\n[03:16.13]吹着南方暖洋洋的哀愁\n[03:20.29]我们小手拉大手\n[03:22.68]今天加油向昨天挥挥手\n[03:27.56]我们小手拉大手\n[03:29.79]今天为我加油\n[03:31.54]舍不得挥挥手\n"},"klyric":{"version":0,"lyric":""},"tlyric":{"version":12,"lyric":"[by:你所不认识的树怪]\n[00:00.90]日语\n[00:08.43]合上一直忘记闭住的双眼，再一次伸出双手\n[00:15.49]找回隐藏在蓝天中的爱恋之歌\n[00:23.06]一定不要忘记，随时陪伴在你身边的时光\n[00:30.06]望着星空，独自一人的黎明\n[00:37.69]唯一的一颗心，请不要在悲伤中度过\n[00:45.05]就连你的叹息，我也要将它化作春风\n[00:52.42]在洒满阳光的坡道上，骑着自行车\n[01:00.28]载着你和那些遗忘了的记忆奔向远方\n[01:07.05]啦啦啦啦啦，染红嘴唇，轻声吟唱着\n[01:15.19]和你一起找到的幸福，就像花儿一样\n[01:22.54]\n[01:24.31]\n[01:27.64]\n[01:31.38]\n[01:34.92]\n[01:38.70]\n[01:42.48]\n[01:45.87]\n[01:49.76]\n[01:53.34]\n[01:57.17]\n[02:00.81]\n[02:04.39]\n[02:07.97]\n[02:09.96]\n[02:11.71]\n[02:15.89]\n[02:18.22]\n[02:19.97]\n[02:22.80]\n[02:24.64]\n[02:26.49]\n[02:30.57]\n[02:32.96]\n[02:45.26]\n[02:57.65]在洒满阳光的坡道上，骑着自行车\n[03:05.46]载着和你一起约定的誓言去到远方\n[03:12.28]\n[03:13.97]\n[03:16.13]\n[03:20.29]\n[03:22.68]\n[03:27.56]\n[03:29.79]\n[03:31.54]\n"},"romalrc":{"version":0,"lyric":""},"code":200}

**Comment by touchmii** [comment]
3.7.6版本已经没有这个问题了,我继续用几天看看有没有类似的情况.

**Comment by anhoder** [comment]
新版已经修复了
