### ISSUE TITLE
能否实现内容自动居中

### ISSUE THREAD

**Issue by 4285f4** [go-musicfox/go-musicfox#81]
如图，遇到比较长的歌词可太难受了
<img width="947" alt="Snipaste_2023-04-03_19-23-36" src="https://user-images.githubusercontent.com/36158676/229495827-95434fbd-7ad9-4d5e-93c1-17a6a1c5d86d.png">

**Comment by anhoder** [comment]
4.0.0会增加歌词滚动，并且针对单列模式会把歌词稍微往中间移动了一点，但是居中显示还没精力做，sry...
