### ISSUE TITLE
收听私人雷达时发生Painc

### ISSUE THREAD

**Issue by ayamir** [go-musicfox/go-musicfox#86]
![image](https://user-images.githubusercontent.com/61657399/230761645-f2d52ef7-6bdb-4fbb-9e40-57a4ff965a6c.png)

![image](https://user-images.githubusercontent.com/61657399/230761705-416ceae4-d290-43ca-930f-95f302c869ff.png)

OS: Gentoo Linux with `clang` USE flag
Shell: fish
Terminal: kitty+tmux

**Comment by anhoder** [comment]
用新版本试下
