### ISSUE TITLE
怎么屏蔽鼠标点击？

### ISSUE THREAD

**Issue by rockxsj** [go-musicfox/go-musicfox#93]
鼠标点击界面反馈总是莫名其妙的，点一个地方莫名其妙就暂停了，然后有时候还会切歌。   能不能直接屏蔽鼠标点击事件？

**Comment by anhoder** [comment]
啥系统，win11吗

**Comment by kylezb** [comment]
> 啥系统，win11吗

大概率是X10 mouse的问题，提了issue没负责人理，[ext-mouse](https://github.com/charmbracelet/bubbletea/tree/ext-mouse) 这个分支已经修复了https://github.com/charmbracelet/bubbletea/issues/718

**Comment by anhoder** [comment]
v4.0.3 增加配置项enableMouseEvent，可屏蔽鼠标事件，后续会更新bubbletea修复该问题

**Comment by rockxsj** [comment]
> 啥系统，win11吗

对的
