### ISSUE TITLE
上下切换歌曲列表的时候出现栈越界

### ISSUE THREAD

**Issue by Jamie-0527** [go-musicfox/go-musicfox#94]
我是使用的是win11，应用程序使用版本是3.7.7
![image](https://user-images.githubusercontent.com/67900877/232367796-46f48574-8ffe-495e-86f2-dad86be8180d.png)
@anhoder

**Comment by kylezb** [comment]
最新版解决了https://github.com/go-musicfox/go-musicfox/releases/tag/v4.0.3
