### ISSUE TITLE
切换歌曲异常

### ISSUE THREAD

**Issue by ChenSino** [go-musicfox/go-musicfox#95]
系统：Manjaro
软件版本：4.0.3
使用快捷键切换歌曲就挂了

![](https://i.imgur.com/uEpP3bG.png)

**Comment by anhoder** [comment]
试试4.0.4

**Comment by anhoder** [comment]
跟这个应该是同一个问题 #77

**Comment by ChenSino** [comment]
> 跟这个应该是同一个问题 #77

老哥，用最新代码编译的出现了新的问题

![image](https://user-images.githubusercontent.com/25560521/233527409-ab9929e7-066a-4ce7-a1dc-9215b6819a01.png)

**Comment by anhoder** [comment]
这是go-mp3的偶现bug，一直都有的 => https://github.com/hajimehoshi/go-mp3/issues/40

**Comment by ChenSino** [comment]
听了一上午没有复现
