### ISSUE TITLE
Lastfm other err: lastfm key或secret为空

### ISSUE THREAD

**Issue by yuioto** [go-musicfox/go-musicfox#98]
### Check for existing issues
检查是否已存在相同issue

- [x] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

Open 12 LastFM, 0 authorize

### Environment / 运行环境

Linux 6.2.12-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:27 +0000 x86_64 GNU/Linux

OS: ArchLinux

build https://aur.archlinux.org/packages/go-musicfox
commit 55e0571b21aa1ac4ef87fc55a4de2d3d399247b5

musicfox Version: v3.7.0

### If applicable, list the error messages you see
如果有错误输出请一并填入

2023/04/28 09:31:33 [ERROR] Lastfm other err: lastfm key或secret为空

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

2023年 04月 28日 星期五 09:43:57 UTC
[musicfox.log](https://github.com/go-musicfox/go-musicfox/files/11352228/musicfox.log)

**Comment by kylezb** [comment]
如果是自己build的话是不带lastfm的api的，需要自行指定

**Comment by st0nie** [comment]
这个包现在不是我维护的，你先去aur评论区说一下？

**Comment by anhoder** [comment]
可能是@Tenshi65535

**Comment by Tenshi65535** [comment]
是我在维护，感谢提醒。

**Comment by ffkjjj** [comment]
@anhoder 请问下，这个 key 和 secret 必须要在编译期指定吗？我如果需要指定我自己的 key, secret, 是否只能重新编译

**Comment by anhoder** [comment]
嗯需要重新编译

**Comment by flemon-y** [comment]
@anhoder 你好我问一下，我在archlinxucn源上安装的包，也同样出现了类似这样的无法授权lastfm,提示lastfm key或secret为空，这个问题是不是也要跟archlinxucn源那边的维护者反应一下？
