### ISSUE TITLE
Windows的cmd渲染问题

### ISSUE THREAD

**Issue by wangcham** [go-musicfox/go-musicfox#99]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

在我进行  搜索歌曲->按照歌手 -> 热门专辑 ，播放专辑里的曲目时，要进行切换歌曲，于是出现以下情况：

![image](https://user-images.githubusercontent.com/95991795/235362583-9bc66392-1663-428c-89ce-e39617d7c44c.png)

点击enter进入专辑：
![image](https://user-images.githubusercontent.com/95991795/235362700-d5953310-db98-4c27-b863-95c053d1b747.png)
于是我们就可以看到专辑页面的上面还有10，11，这是热门专辑页面的，现在向右，调整到序号为一的kite曲目：
![image](https://user-images.githubusercontent.com/95991795/235362773-ea8cf198-9b05-48e6-9882-62cded65e667.png)
向下调整按钮，出现：
![image](https://user-images.githubusercontent.com/95991795/235362811-77d74ca3-37a7-41c2-b954-43ee022aed19.png)
向左：
![image](https://user-images.githubusercontent.com/95991795/235362819-829a8d4d-b5ea-4c9e-8e4e-22b12a4fa64f.png)
就是这样的，出现的歌曲乱套了。

### Environment / 运行环境

设备名称	LAPTOP-QCJ66DOC
处理器	11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz   3.11 GHz
系统类型	64 位操作系统, 基于 x64 的处理器

**Comment by anhoder** [comment]
windows下在Windows Terminal里打开吧，cmd下可能会有问题，现在不会对cmd做特殊兼容了
